// Code generated by ent, DO NOT EDIT.

package relayratesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relayratesnapshot type in the database.
	Label = "relay_rate_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMonitorID holds the string denoting the monitor_id field in the database.
	FieldMonitorID = "monitor_id"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMonitor holds the string denoting the monitor edge name in mutations.
	EdgeMonitor = "monitor"
	// Table holds the table name of the relayratesnapshot in the database.
	Table = "relay_rate_snapshots"
	// MonitorTable is the table that holds the monitor relation/edge.
	MonitorTable = "relay_rate_snapshots"
	// MonitorInverseTable is the table name for the RelayMonitor entity.
	// It exists in this package in order to avoid circular dependency with the "relaymonitor" package.
	MonitorInverseTable = "relay_monitors"
	// MonitorColumn is the table column denoting the monitor relation/edge.
	MonitorColumn = "monitor_id"
)

// Columns holds all SQL columns for relayratesnapshot fields.
var Columns = []string{
	FieldID,
	FieldMonitorID,
	FieldGroupName,
	FieldRate,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RelayRateSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMonitorID orders the results by the monitor_id field.
func ByMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitorID, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMonitorField orders the results by monitor field.
func ByMonitorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitorStep(), sql.OrderByField(field, opts...))
	}
}
func newMonitorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
	)
}
