// Code generated by ent, DO NOT EDIT.

package relaymonitor

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relaymonitor type in the database.
	Label = "relay_monitor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSystem holds the string denoting the system field in the database.
	FieldSystem = "system"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldVendor holds the string denoting the vendor field in the database.
	FieldVendor = "vendor"
	// FieldAuthAccount holds the string denoting the auth_account field in the database.
	FieldAuthAccount = "auth_account"
	// FieldCredentialEncrypted holds the string denoting the credential_encrypted field in the database.
	FieldCredentialEncrypted = "credential_encrypted"
	// FieldWatchedGroups holds the string denoting the watched_groups field in the database.
	FieldWatchedGroups = "watched_groups"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldIntervalSeconds holds the string denoting the interval_seconds field in the database.
	FieldIntervalSeconds = "interval_seconds"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// EdgeSnapshots holds the string denoting the snapshots edge name in mutations.
	EdgeSnapshots = "snapshots"
	// EdgeChanges holds the string denoting the changes edge name in mutations.
	EdgeChanges = "changes"
	// Table holds the table name of the relaymonitor in the database.
	Table = "relay_monitors"
	// SnapshotsTable is the table that holds the snapshots relation/edge.
	SnapshotsTable = "relay_rate_snapshots"
	// SnapshotsInverseTable is the table name for the RelayRateSnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "relayratesnapshot" package.
	SnapshotsInverseTable = "relay_rate_snapshots"
	// SnapshotsColumn is the table column denoting the snapshots relation/edge.
	SnapshotsColumn = "monitor_id"
	// ChangesTable is the table that holds the changes relation/edge.
	ChangesTable = "relay_rate_changes"
	// ChangesInverseTable is the table name for the RelayRateChange entity.
	// It exists in this package in order to avoid circular dependency with the "relayratechange" package.
	ChangesInverseTable = "relay_rate_changes"
	// ChangesColumn is the table column denoting the changes relation/edge.
	ChangesColumn = "monitor_id"
)

// Columns holds all SQL columns for relaymonitor fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldSystem,
	FieldBaseURL,
	FieldVendor,
	FieldAuthAccount,
	FieldCredentialEncrypted,
	FieldWatchedGroups,
	FieldEnabled,
	FieldIntervalSeconds,
	FieldLastCheckedAt,
	FieldLastError,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// DefaultVendor holds the default value on creation for the "vendor" field.
	DefaultVendor string
	// VendorValidator is a validator for the "vendor" field. It is called by the builders before save.
	VendorValidator func(string) error
	// DefaultAuthAccount holds the default value on creation for the "auth_account" field.
	DefaultAuthAccount string
	// AuthAccountValidator is a validator for the "auth_account" field. It is called by the builders before save.
	AuthAccountValidator func(string) error
	// DefaultCredentialEncrypted holds the default value on creation for the "credential_encrypted" field.
	DefaultCredentialEncrypted string
	// DefaultWatchedGroups holds the default value on creation for the "watched_groups" field.
	DefaultWatchedGroups []string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultIntervalSeconds holds the default value on creation for the "interval_seconds" field.
	DefaultIntervalSeconds int
	// IntervalSecondsValidator is a validator for the "interval_seconds" field. It is called by the builders before save.
	IntervalSecondsValidator func(int) error
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	LastErrorValidator func(string) error
)

// System defines the type for the "system" enum field.
type System string

// System values.
const (
	SystemSub2api System = "sub2api"
	SystemNewapi  System = "newapi"
)

func (s System) String() string {
	return string(s)
}

// SystemValidator is a validator for the "system" field enum values. It is called by the builders before save.
func SystemValidator(s System) error {
	switch s {
	case SystemSub2api, SystemNewapi:
		return nil
	default:
		return fmt.Errorf("relaymonitor: invalid enum value for system field: %q", s)
	}
}

// OrderOption defines the ordering options for the RelayMonitor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySystem orders the results by the system field.
func BySystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystem, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByVendor orders the results by the vendor field.
func ByVendor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVendor, opts...).ToFunc()
}

// ByAuthAccount orders the results by the auth_account field.
func ByAuthAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthAccount, opts...).ToFunc()
}

// ByCredentialEncrypted orders the results by the credential_encrypted field.
func ByCredentialEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialEncrypted, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByIntervalSeconds orders the results by the interval_seconds field.
func ByIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalSeconds, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// BySnapshotsCount orders the results by snapshots count.
func BySnapshotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSnapshotsStep(), opts...)
	}
}

// BySnapshots orders the results by snapshots terms.
func BySnapshots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChangesCount orders the results by changes count.
func ByChangesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChangesStep(), opts...)
	}
}

// ByChanges orders the results by changes terms.
func ByChanges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChangesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSnapshotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
	)
}
func newChangesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChangesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChangesTable, ChangesColumn),
	)
}
