// Code generated by ent, DO NOT EDIT.

package relaymonitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldBaseURL, v))
}

// Vendor applies equality check predicate on the "vendor" field. It's identical to VendorEQ.
func Vendor(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldVendor, v))
}

// CredentialEncrypted applies equality check predicate on the "credential_encrypted" field. It's identical to CredentialEncryptedEQ.
func CredentialEncrypted(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldCredentialEncrypted, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldEnabled, v))
}

// IntervalSeconds applies equality check predicate on the "interval_seconds" field. It's identical to IntervalSecondsEQ.
func IntervalSeconds(v int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldIntervalSeconds, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldLastError, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContainsFold(FieldName, v))
}

// SystemEQ applies the EQ predicate on the "system" field.
func SystemEQ(v System) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldSystem, v))
}

// SystemNEQ applies the NEQ predicate on the "system" field.
func SystemNEQ(v System) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldSystem, v))
}

// SystemIn applies the In predicate on the "system" field.
func SystemIn(vs ...System) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldSystem, vs...))
}

// SystemNotIn applies the NotIn predicate on the "system" field.
func SystemNotIn(vs ...System) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldSystem, vs...))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContainsFold(FieldBaseURL, v))
}

// VendorEQ applies the EQ predicate on the "vendor" field.
func VendorEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldVendor, v))
}

// VendorNEQ applies the NEQ predicate on the "vendor" field.
func VendorNEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldVendor, v))
}

// VendorIn applies the In predicate on the "vendor" field.
func VendorIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldVendor, vs...))
}

// VendorNotIn applies the NotIn predicate on the "vendor" field.
func VendorNotIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldVendor, vs...))
}

// VendorGT applies the GT predicate on the "vendor" field.
func VendorGT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldVendor, v))
}

// VendorGTE applies the GTE predicate on the "vendor" field.
func VendorGTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldVendor, v))
}

// VendorLT applies the LT predicate on the "vendor" field.
func VendorLT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldVendor, v))
}

// VendorLTE applies the LTE predicate on the "vendor" field.
func VendorLTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldVendor, v))
}

// VendorContains applies the Contains predicate on the "vendor" field.
func VendorContains(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContains(FieldVendor, v))
}

// VendorHasPrefix applies the HasPrefix predicate on the "vendor" field.
func VendorHasPrefix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasPrefix(FieldVendor, v))
}

// VendorHasSuffix applies the HasSuffix predicate on the "vendor" field.
func VendorHasSuffix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasSuffix(FieldVendor, v))
}

// VendorIsNil applies the IsNil predicate on the "vendor" field.
func VendorIsNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIsNull(FieldVendor))
}

// VendorNotNil applies the NotNil predicate on the "vendor" field.
func VendorNotNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotNull(FieldVendor))
}

// VendorEqualFold applies the EqualFold predicate on the "vendor" field.
func VendorEqualFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEqualFold(FieldVendor, v))
}

// VendorContainsFold applies the ContainsFold predicate on the "vendor" field.
func VendorContainsFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContainsFold(FieldVendor, v))
}

// CredentialEncryptedEQ applies the EQ predicate on the "credential_encrypted" field.
func CredentialEncryptedEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldCredentialEncrypted, v))
}

// CredentialEncryptedNEQ applies the NEQ predicate on the "credential_encrypted" field.
func CredentialEncryptedNEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldCredentialEncrypted, v))
}

// CredentialEncryptedIn applies the In predicate on the "credential_encrypted" field.
func CredentialEncryptedIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldCredentialEncrypted, vs...))
}

// CredentialEncryptedNotIn applies the NotIn predicate on the "credential_encrypted" field.
func CredentialEncryptedNotIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldCredentialEncrypted, vs...))
}

// CredentialEncryptedGT applies the GT predicate on the "credential_encrypted" field.
func CredentialEncryptedGT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldCredentialEncrypted, v))
}

// CredentialEncryptedGTE applies the GTE predicate on the "credential_encrypted" field.
func CredentialEncryptedGTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldCredentialEncrypted, v))
}

// CredentialEncryptedLT applies the LT predicate on the "credential_encrypted" field.
func CredentialEncryptedLT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldCredentialEncrypted, v))
}

// CredentialEncryptedLTE applies the LTE predicate on the "credential_encrypted" field.
func CredentialEncryptedLTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldCredentialEncrypted, v))
}

// CredentialEncryptedContains applies the Contains predicate on the "credential_encrypted" field.
func CredentialEncryptedContains(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContains(FieldCredentialEncrypted, v))
}

// CredentialEncryptedHasPrefix applies the HasPrefix predicate on the "credential_encrypted" field.
func CredentialEncryptedHasPrefix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasPrefix(FieldCredentialEncrypted, v))
}

// CredentialEncryptedHasSuffix applies the HasSuffix predicate on the "credential_encrypted" field.
func CredentialEncryptedHasSuffix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasSuffix(FieldCredentialEncrypted, v))
}

// CredentialEncryptedIsNil applies the IsNil predicate on the "credential_encrypted" field.
func CredentialEncryptedIsNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIsNull(FieldCredentialEncrypted))
}

// CredentialEncryptedNotNil applies the NotNil predicate on the "credential_encrypted" field.
func CredentialEncryptedNotNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotNull(FieldCredentialEncrypted))
}

// CredentialEncryptedEqualFold applies the EqualFold predicate on the "credential_encrypted" field.
func CredentialEncryptedEqualFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEqualFold(FieldCredentialEncrypted, v))
}

// CredentialEncryptedContainsFold applies the ContainsFold predicate on the "credential_encrypted" field.
func CredentialEncryptedContainsFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContainsFold(FieldCredentialEncrypted, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldEnabled, v))
}

// IntervalSecondsEQ applies the EQ predicate on the "interval_seconds" field.
func IntervalSecondsEQ(v int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsNEQ applies the NEQ predicate on the "interval_seconds" field.
func IntervalSecondsNEQ(v int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsIn applies the In predicate on the "interval_seconds" field.
func IntervalSecondsIn(vs ...int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsNotIn applies the NotIn predicate on the "interval_seconds" field.
func IntervalSecondsNotIn(vs ...int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsGT applies the GT predicate on the "interval_seconds" field.
func IntervalSecondsGT(v int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldIntervalSeconds, v))
}

// IntervalSecondsGTE applies the GTE predicate on the "interval_seconds" field.
func IntervalSecondsGTE(v int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldIntervalSeconds, v))
}

// IntervalSecondsLT applies the LT predicate on the "interval_seconds" field.
func IntervalSecondsLT(v int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldIntervalSeconds, v))
}

// IntervalSecondsLTE applies the LTE predicate on the "interval_seconds" field.
func IntervalSecondsLTE(v int) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldIntervalSeconds, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotNull(FieldLastCheckedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.FieldLTE(FieldCreatedBy, v))
}

// HasSnapshots applies the HasEdge predicate on the "snapshots" edge.
func HasSnapshots() predicate.RelayMonitor {
	return predicate.RelayMonitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotsWith applies the HasEdge predicate on the "snapshots" edge with a given conditions (other predicates).
func HasSnapshotsWith(preds ...predicate.RelayRateSnapshot) predicate.RelayMonitor {
	return predicate.RelayMonitor(func(s *sql.Selector) {
		step := newSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChanges applies the HasEdge predicate on the "changes" edge.
func HasChanges() predicate.RelayMonitor {
	return predicate.RelayMonitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChangesTable, ChangesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChangesWith applies the HasEdge predicate on the "changes" edge with a given conditions (other predicates).
func HasChangesWith(preds ...predicate.RelayRateChange) predicate.RelayMonitor {
	return predicate.RelayMonitor(func(s *sql.Selector) {
		step := newChangesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelayMonitor) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelayMonitor) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelayMonitor) predicate.RelayMonitor {
	return predicate.RelayMonitor(sql.NotPredicates(p))
}
