// Code generated by ent, DO NOT EDIT.

package relayratechange

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the relayratechange type in the database.
	Label = "relay_rate_change"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMonitorID holds the string denoting the monitor_id field in the database.
	FieldMonitorID = "monitor_id"
	// FieldSite holds the string denoting the site field in the database.
	FieldSite = "site"
	// FieldSystem holds the string denoting the system field in the database.
	FieldSystem = "system"
	// FieldVendor holds the string denoting the vendor field in the database.
	FieldVendor = "vendor"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldOldRate holds the string denoting the old_rate field in the database.
	FieldOldRate = "old_rate"
	// FieldNewRate holds the string denoting the new_rate field in the database.
	FieldNewRate = "new_rate"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldDetectedAt holds the string denoting the detected_at field in the database.
	FieldDetectedAt = "detected_at"
	// EdgeMonitor holds the string denoting the monitor edge name in mutations.
	EdgeMonitor = "monitor"
	// Table holds the table name of the relayratechange in the database.
	Table = "relay_rate_changes"
	// MonitorTable is the table that holds the monitor relation/edge.
	MonitorTable = "relay_rate_changes"
	// MonitorInverseTable is the table name for the RelayMonitor entity.
	// It exists in this package in order to avoid circular dependency with the "relaymonitor" package.
	MonitorInverseTable = "relay_monitors"
	// MonitorColumn is the table column denoting the monitor relation/edge.
	MonitorColumn = "monitor_id"
)

// Columns holds all SQL columns for relayratechange fields.
var Columns = []string{
	FieldID,
	FieldMonitorID,
	FieldSite,
	FieldSystem,
	FieldVendor,
	FieldGroupName,
	FieldOldRate,
	FieldNewRate,
	FieldDirection,
	FieldContent,
	FieldDetectedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SiteValidator is a validator for the "site" field. It is called by the builders before save.
	SiteValidator func(string) error
	// SystemValidator is a validator for the "system" field. It is called by the builders before save.
	SystemValidator func(string) error
	// DefaultVendor holds the default value on creation for the "vendor" field.
	DefaultVendor string
	// VendorValidator is a validator for the "vendor" field. It is called by the builders before save.
	VendorValidator func(string) error
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultDetectedAt holds the default value on creation for the "detected_at" field.
	DefaultDetectedAt func() time.Time
)

// Direction defines the type for the "direction" enum field.
type Direction string

// Direction values.
const (
	DirectionUp   Direction = "up"
	DirectionDown Direction = "down"
)

func (d Direction) String() string {
	return string(d)
}

// DirectionValidator is a validator for the "direction" field enum values. It is called by the builders before save.
func DirectionValidator(d Direction) error {
	switch d {
	case DirectionUp, DirectionDown:
		return nil
	default:
		return fmt.Errorf("relayratechange: invalid enum value for direction field: %q", d)
	}
}

// OrderOption defines the ordering options for the RelayRateChange queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMonitorID orders the results by the monitor_id field.
func ByMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitorID, opts...).ToFunc()
}

// BySite orders the results by the site field.
func BySite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSite, opts...).ToFunc()
}

// BySystem orders the results by the system field.
func BySystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystem, opts...).ToFunc()
}

// ByVendor orders the results by the vendor field.
func ByVendor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVendor, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByOldRate orders the results by the old_rate field.
func ByOldRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOldRate, opts...).ToFunc()
}

// ByNewRate orders the results by the new_rate field.
func ByNewRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewRate, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByDetectedAt orders the results by the detected_at field.
func ByDetectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetectedAt, opts...).ToFunc()
}

// ByMonitorField orders the results by monitor field.
func ByMonitorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitorStep(), sql.OrderByField(field, opts...))
	}
}
func newMonitorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
	)
}
