// Code generated by ent, DO NOT EDIT.

package relayratechange

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldID, id))
}

// MonitorID applies equality check predicate on the "monitor_id" field. It's identical to MonitorIDEQ.
func MonitorID(v int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldMonitorID, v))
}

// Site applies equality check predicate on the "site" field. It's identical to SiteEQ.
func Site(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldSite, v))
}

// System applies equality check predicate on the "system" field. It's identical to SystemEQ.
func System(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldSystem, v))
}

// Vendor applies equality check predicate on the "vendor" field. It's identical to VendorEQ.
func Vendor(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldVendor, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldGroupName, v))
}

// OldRate applies equality check predicate on the "old_rate" field. It's identical to OldRateEQ.
func OldRate(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldOldRate, v))
}

// NewRate applies equality check predicate on the "new_rate" field. It's identical to NewRateEQ.
func NewRate(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldNewRate, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldContent, v))
}

// DetectedAt applies equality check predicate on the "detected_at" field. It's identical to DetectedAtEQ.
func DetectedAt(v time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldDetectedAt, v))
}

// MonitorIDEQ applies the EQ predicate on the "monitor_id" field.
func MonitorIDEQ(v int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldMonitorID, v))
}

// MonitorIDNEQ applies the NEQ predicate on the "monitor_id" field.
func MonitorIDNEQ(v int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldMonitorID, v))
}

// MonitorIDIn applies the In predicate on the "monitor_id" field.
func MonitorIDIn(vs ...int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldMonitorID, vs...))
}

// MonitorIDNotIn applies the NotIn predicate on the "monitor_id" field.
func MonitorIDNotIn(vs ...int64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldMonitorID, vs...))
}

// SiteEQ applies the EQ predicate on the "site" field.
func SiteEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldSite, v))
}

// SiteNEQ applies the NEQ predicate on the "site" field.
func SiteNEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldSite, v))
}

// SiteIn applies the In predicate on the "site" field.
func SiteIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldSite, vs...))
}

// SiteNotIn applies the NotIn predicate on the "site" field.
func SiteNotIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldSite, vs...))
}

// SiteGT applies the GT predicate on the "site" field.
func SiteGT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldSite, v))
}

// SiteGTE applies the GTE predicate on the "site" field.
func SiteGTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldSite, v))
}

// SiteLT applies the LT predicate on the "site" field.
func SiteLT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldSite, v))
}

// SiteLTE applies the LTE predicate on the "site" field.
func SiteLTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldSite, v))
}

// SiteContains applies the Contains predicate on the "site" field.
func SiteContains(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContains(FieldSite, v))
}

// SiteHasPrefix applies the HasPrefix predicate on the "site" field.
func SiteHasPrefix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasPrefix(FieldSite, v))
}

// SiteHasSuffix applies the HasSuffix predicate on the "site" field.
func SiteHasSuffix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasSuffix(FieldSite, v))
}

// SiteEqualFold applies the EqualFold predicate on the "site" field.
func SiteEqualFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEqualFold(FieldSite, v))
}

// SiteContainsFold applies the ContainsFold predicate on the "site" field.
func SiteContainsFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContainsFold(FieldSite, v))
}

// SystemEQ applies the EQ predicate on the "system" field.
func SystemEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldSystem, v))
}

// SystemNEQ applies the NEQ predicate on the "system" field.
func SystemNEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldSystem, v))
}

// SystemIn applies the In predicate on the "system" field.
func SystemIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldSystem, vs...))
}

// SystemNotIn applies the NotIn predicate on the "system" field.
func SystemNotIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldSystem, vs...))
}

// SystemGT applies the GT predicate on the "system" field.
func SystemGT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldSystem, v))
}

// SystemGTE applies the GTE predicate on the "system" field.
func SystemGTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldSystem, v))
}

// SystemLT applies the LT predicate on the "system" field.
func SystemLT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldSystem, v))
}

// SystemLTE applies the LTE predicate on the "system" field.
func SystemLTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldSystem, v))
}

// SystemContains applies the Contains predicate on the "system" field.
func SystemContains(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContains(FieldSystem, v))
}

// SystemHasPrefix applies the HasPrefix predicate on the "system" field.
func SystemHasPrefix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasPrefix(FieldSystem, v))
}

// SystemHasSuffix applies the HasSuffix predicate on the "system" field.
func SystemHasSuffix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasSuffix(FieldSystem, v))
}

// SystemEqualFold applies the EqualFold predicate on the "system" field.
func SystemEqualFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEqualFold(FieldSystem, v))
}

// SystemContainsFold applies the ContainsFold predicate on the "system" field.
func SystemContainsFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContainsFold(FieldSystem, v))
}

// VendorEQ applies the EQ predicate on the "vendor" field.
func VendorEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldVendor, v))
}

// VendorNEQ applies the NEQ predicate on the "vendor" field.
func VendorNEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldVendor, v))
}

// VendorIn applies the In predicate on the "vendor" field.
func VendorIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldVendor, vs...))
}

// VendorNotIn applies the NotIn predicate on the "vendor" field.
func VendorNotIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldVendor, vs...))
}

// VendorGT applies the GT predicate on the "vendor" field.
func VendorGT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldVendor, v))
}

// VendorGTE applies the GTE predicate on the "vendor" field.
func VendorGTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldVendor, v))
}

// VendorLT applies the LT predicate on the "vendor" field.
func VendorLT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldVendor, v))
}

// VendorLTE applies the LTE predicate on the "vendor" field.
func VendorLTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldVendor, v))
}

// VendorContains applies the Contains predicate on the "vendor" field.
func VendorContains(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContains(FieldVendor, v))
}

// VendorHasPrefix applies the HasPrefix predicate on the "vendor" field.
func VendorHasPrefix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasPrefix(FieldVendor, v))
}

// VendorHasSuffix applies the HasSuffix predicate on the "vendor" field.
func VendorHasSuffix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasSuffix(FieldVendor, v))
}

// VendorIsNil applies the IsNil predicate on the "vendor" field.
func VendorIsNil() predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIsNull(FieldVendor))
}

// VendorNotNil applies the NotNil predicate on the "vendor" field.
func VendorNotNil() predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotNull(FieldVendor))
}

// VendorEqualFold applies the EqualFold predicate on the "vendor" field.
func VendorEqualFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEqualFold(FieldVendor, v))
}

// VendorContainsFold applies the ContainsFold predicate on the "vendor" field.
func VendorContainsFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContainsFold(FieldVendor, v))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContainsFold(FieldGroupName, v))
}

// OldRateEQ applies the EQ predicate on the "old_rate" field.
func OldRateEQ(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldOldRate, v))
}

// OldRateNEQ applies the NEQ predicate on the "old_rate" field.
func OldRateNEQ(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldOldRate, v))
}

// OldRateIn applies the In predicate on the "old_rate" field.
func OldRateIn(vs ...float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldOldRate, vs...))
}

// OldRateNotIn applies the NotIn predicate on the "old_rate" field.
func OldRateNotIn(vs ...float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldOldRate, vs...))
}

// OldRateGT applies the GT predicate on the "old_rate" field.
func OldRateGT(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldOldRate, v))
}

// OldRateGTE applies the GTE predicate on the "old_rate" field.
func OldRateGTE(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldOldRate, v))
}

// OldRateLT applies the LT predicate on the "old_rate" field.
func OldRateLT(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldOldRate, v))
}

// OldRateLTE applies the LTE predicate on the "old_rate" field.
func OldRateLTE(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldOldRate, v))
}

// NewRateEQ applies the EQ predicate on the "new_rate" field.
func NewRateEQ(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldNewRate, v))
}

// NewRateNEQ applies the NEQ predicate on the "new_rate" field.
func NewRateNEQ(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldNewRate, v))
}

// NewRateIn applies the In predicate on the "new_rate" field.
func NewRateIn(vs ...float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldNewRate, vs...))
}

// NewRateNotIn applies the NotIn predicate on the "new_rate" field.
func NewRateNotIn(vs ...float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldNewRate, vs...))
}

// NewRateGT applies the GT predicate on the "new_rate" field.
func NewRateGT(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldNewRate, v))
}

// NewRateGTE applies the GTE predicate on the "new_rate" field.
func NewRateGTE(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldNewRate, v))
}

// NewRateLT applies the LT predicate on the "new_rate" field.
func NewRateLT(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldNewRate, v))
}

// NewRateLTE applies the LTE predicate on the "new_rate" field.
func NewRateLTE(v float64) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldNewRate, v))
}

// DirectionEQ applies the EQ predicate on the "direction" field.
func DirectionEQ(v Direction) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldDirection, v))
}

// DirectionNEQ applies the NEQ predicate on the "direction" field.
func DirectionNEQ(v Direction) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldDirection, v))
}

// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...Direction) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldDirection, vs...))
}

// DirectionNotIn applies the NotIn predicate on the "direction" field.
func DirectionNotIn(vs ...Direction) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldDirection, vs...))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldContainsFold(FieldContent, v))
}

// DetectedAtEQ applies the EQ predicate on the "detected_at" field.
func DetectedAtEQ(v time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldEQ(FieldDetectedAt, v))
}

// DetectedAtNEQ applies the NEQ predicate on the "detected_at" field.
func DetectedAtNEQ(v time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNEQ(FieldDetectedAt, v))
}

// DetectedAtIn applies the In predicate on the "detected_at" field.
func DetectedAtIn(vs ...time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldIn(FieldDetectedAt, vs...))
}

// DetectedAtNotIn applies the NotIn predicate on the "detected_at" field.
func DetectedAtNotIn(vs ...time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldNotIn(FieldDetectedAt, vs...))
}

// DetectedAtGT applies the GT predicate on the "detected_at" field.
func DetectedAtGT(v time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGT(FieldDetectedAt, v))
}

// DetectedAtGTE applies the GTE predicate on the "detected_at" field.
func DetectedAtGTE(v time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldGTE(FieldDetectedAt, v))
}

// DetectedAtLT applies the LT predicate on the "detected_at" field.
func DetectedAtLT(v time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLT(FieldDetectedAt, v))
}

// DetectedAtLTE applies the LTE predicate on the "detected_at" field.
func DetectedAtLTE(v time.Time) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.FieldLTE(FieldDetectedAt, v))
}

// HasMonitor applies the HasEdge predicate on the "monitor" edge.
func HasMonitor() predicate.RelayRateChange {
	return predicate.RelayRateChange(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMonitorWith applies the HasEdge predicate on the "monitor" edge with a given conditions (other predicates).
func HasMonitorWith(preds ...predicate.RelayMonitor) predicate.RelayRateChange {
	return predicate.RelayRateChange(func(s *sql.Selector) {
		step := newMonitorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelayRateChange) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelayRateChange) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelayRateChange) predicate.RelayRateChange {
	return predicate.RelayRateChange(sql.NotPredicates(p))
}
