// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratechange"
	"github.com/Wei-Shaw/sub2api/ent/relayratesnapshot"
)

// RelayMonitorCreate is the builder for creating a RelayMonitor entity.
type RelayMonitorCreate struct {
	config
	mutation *RelayMonitorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelayMonitorCreate) SetCreatedAt(v time.Time) *RelayMonitorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableCreatedAt(v *time.Time) *RelayMonitorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelayMonitorCreate) SetUpdatedAt(v time.Time) *RelayMonitorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableUpdatedAt(v *time.Time) *RelayMonitorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RelayMonitorCreate) SetName(v string) *RelayMonitorCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSystem sets the "system" field.
func (_c *RelayMonitorCreate) SetSystem(v relaymonitor.System) *RelayMonitorCreate {
	_c.mutation.SetSystem(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *RelayMonitorCreate) SetBaseURL(v string) *RelayMonitorCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetVendor sets the "vendor" field.
func (_c *RelayMonitorCreate) SetVendor(v string) *RelayMonitorCreate {
	_c.mutation.SetVendor(v)
	return _c
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableVendor(v *string) *RelayMonitorCreate {
	if v != nil {
		_c.SetVendor(*v)
	}
	return _c
}

// SetAuthAccount sets the "auth_account" field.
func (_c *RelayMonitorCreate) SetAuthAccount(v string) *RelayMonitorCreate {
	_c.mutation.SetAuthAccount(v)
	return _c
}

// SetNillableAuthAccount sets the "auth_account" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableAuthAccount(v *string) *RelayMonitorCreate {
	if v != nil {
		_c.SetAuthAccount(*v)
	}
	return _c
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_c *RelayMonitorCreate) SetCredentialEncrypted(v string) *RelayMonitorCreate {
	_c.mutation.SetCredentialEncrypted(v)
	return _c
}

// SetNillableCredentialEncrypted sets the "credential_encrypted" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableCredentialEncrypted(v *string) *RelayMonitorCreate {
	if v != nil {
		_c.SetCredentialEncrypted(*v)
	}
	return _c
}

// SetWatchedGroups sets the "watched_groups" field.
func (_c *RelayMonitorCreate) SetWatchedGroups(v []string) *RelayMonitorCreate {
	_c.mutation.SetWatchedGroups(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RelayMonitorCreate) SetEnabled(v bool) *RelayMonitorCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableEnabled(v *bool) *RelayMonitorCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_c *RelayMonitorCreate) SetIntervalSeconds(v int) *RelayMonitorCreate {
	_c.mutation.SetIntervalSeconds(v)
	return _c
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableIntervalSeconds(v *int) *RelayMonitorCreate {
	if v != nil {
		_c.SetIntervalSeconds(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *RelayMonitorCreate) SetLastCheckedAt(v time.Time) *RelayMonitorCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableLastCheckedAt(v *time.Time) *RelayMonitorCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *RelayMonitorCreate) SetLastError(v string) *RelayMonitorCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *RelayMonitorCreate) SetNillableLastError(v *string) *RelayMonitorCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *RelayMonitorCreate) SetCreatedBy(v int64) *RelayMonitorCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// AddSnapshotIDs adds the "snapshots" edge to the RelayRateSnapshot entity by IDs.
func (_c *RelayMonitorCreate) AddSnapshotIDs(ids ...int64) *RelayMonitorCreate {
	_c.mutation.AddSnapshotIDs(ids...)
	return _c
}

// AddSnapshots adds the "snapshots" edges to the RelayRateSnapshot entity.
func (_c *RelayMonitorCreate) AddSnapshots(v ...*RelayRateSnapshot) *RelayMonitorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSnapshotIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the RelayRateChange entity by IDs.
func (_c *RelayMonitorCreate) AddChangeIDs(ids ...int64) *RelayMonitorCreate {
	_c.mutation.AddChangeIDs(ids...)
	return _c
}

// AddChanges adds the "changes" edges to the RelayRateChange entity.
func (_c *RelayMonitorCreate) AddChanges(v ...*RelayRateChange) *RelayMonitorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChangeIDs(ids...)
}

// Mutation returns the RelayMonitorMutation object of the builder.
func (_c *RelayMonitorCreate) Mutation() *RelayMonitorMutation {
	return _c.mutation
}

// Save creates the RelayMonitor in the database.
func (_c *RelayMonitorCreate) Save(ctx context.Context) (*RelayMonitor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelayMonitorCreate) SaveX(ctx context.Context) *RelayMonitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayMonitorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayMonitorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelayMonitorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := relaymonitor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := relaymonitor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Vendor(); !ok {
		v := relaymonitor.DefaultVendor
		_c.mutation.SetVendor(v)
	}
	if _, ok := _c.mutation.AuthAccount(); !ok {
		v := relaymonitor.DefaultAuthAccount
		_c.mutation.SetAuthAccount(v)
	}
	if _, ok := _c.mutation.CredentialEncrypted(); !ok {
		v := relaymonitor.DefaultCredentialEncrypted
		_c.mutation.SetCredentialEncrypted(v)
	}
	if _, ok := _c.mutation.WatchedGroups(); !ok {
		v := relaymonitor.DefaultWatchedGroups
		_c.mutation.SetWatchedGroups(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := relaymonitor.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		v := relaymonitor.DefaultIntervalSeconds
		_c.mutation.SetIntervalSeconds(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := relaymonitor.DefaultLastError
		_c.mutation.SetLastError(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelayMonitorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RelayMonitor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RelayMonitor.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RelayMonitor.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := relaymonitor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.System(); !ok {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required field "RelayMonitor.system"`)}
	}
	if v, ok := _c.mutation.System(); ok {
		if err := relaymonitor.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.system": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "RelayMonitor.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := relaymonitor.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.base_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Vendor(); ok {
		if err := relaymonitor.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.vendor": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AuthAccount(); ok {
		if err := relaymonitor.AuthAccountValidator(v); err != nil {
			return &ValidationError{Name: "auth_account", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.auth_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WatchedGroups(); !ok {
		return &ValidationError{Name: "watched_groups", err: errors.New(`ent: missing required field "RelayMonitor.watched_groups"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RelayMonitor.enabled"`)}
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		return &ValidationError{Name: "interval_seconds", err: errors.New(`ent: missing required field "RelayMonitor.interval_seconds"`)}
	}
	if v, ok := _c.mutation.IntervalSeconds(); ok {
		if err := relaymonitor.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := relaymonitor.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.last_error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "RelayMonitor.created_by"`)}
	}
	return nil
}

func (_c *RelayMonitorCreate) sqlSave(ctx context.Context) (*RelayMonitor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelayMonitorCreate) createSpec() (*RelayMonitor, *sqlgraph.CreateSpec) {
	var (
		_node = &RelayMonitor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relaymonitor.Table, sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relaymonitor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relaymonitor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(relaymonitor.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.System(); ok {
		_spec.SetField(relaymonitor.FieldSystem, field.TypeEnum, value)
		_node.System = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(relaymonitor.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Vendor(); ok {
		_spec.SetField(relaymonitor.FieldVendor, field.TypeString, value)
		_node.Vendor = value
	}
	if value, ok := _c.mutation.AuthAccount(); ok {
		_spec.SetField(relaymonitor.FieldAuthAccount, field.TypeString, value)
		_node.AuthAccount = value
	}
	if value, ok := _c.mutation.CredentialEncrypted(); ok {
		_spec.SetField(relaymonitor.FieldCredentialEncrypted, field.TypeString, value)
		_node.CredentialEncrypted = value
	}
	if value, ok := _c.mutation.WatchedGroups(); ok {
		_spec.SetField(relaymonitor.FieldWatchedGroups, field.TypeJSON, value)
		_node.WatchedGroups = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(relaymonitor.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.IntervalSeconds(); ok {
		_spec.SetField(relaymonitor.FieldIntervalSeconds, field.TypeInt, value)
		_node.IntervalSeconds = value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(relaymonitor.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(relaymonitor.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(relaymonitor.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.SnapshotsTable,
			Columns: []string{relaymonitor.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.ChangesTable,
			Columns: []string{relaymonitor.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayMonitor.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayMonitorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayMonitorCreate) OnConflict(opts ...sql.ConflictOption) *RelayMonitorUpsertOne {
	_c.conflict = opts
	return &RelayMonitorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayMonitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayMonitorCreate) OnConflictColumns(columns ...string) *RelayMonitorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayMonitorUpsertOne{
		create: _c,
	}
}

type (
	// RelayMonitorUpsertOne is the builder for "upsert"-ing
	//  one RelayMonitor node.
	RelayMonitorUpsertOne struct {
		create *RelayMonitorCreate
	}

	// RelayMonitorUpsert is the "OnConflict" setter.
	RelayMonitorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayMonitorUpsert) SetUpdatedAt(v time.Time) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateUpdatedAt() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *RelayMonitorUpsert) SetName(v string) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateName() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldName)
	return u
}

// SetSystem sets the "system" field.
func (u *RelayMonitorUpsert) SetSystem(v relaymonitor.System) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldSystem, v)
	return u
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateSystem() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldSystem)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *RelayMonitorUpsert) SetBaseURL(v string) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateBaseURL() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldBaseURL)
	return u
}

// SetVendor sets the "vendor" field.
func (u *RelayMonitorUpsert) SetVendor(v string) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldVendor, v)
	return u
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateVendor() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldVendor)
	return u
}

// ClearVendor clears the value of the "vendor" field.
func (u *RelayMonitorUpsert) ClearVendor() *RelayMonitorUpsert {
	u.SetNull(relaymonitor.FieldVendor)
	return u
}

// SetAuthAccount sets the "auth_account" field.
func (u *RelayMonitorUpsert) SetAuthAccount(v string) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldAuthAccount, v)
	return u
}

// UpdateAuthAccount sets the "auth_account" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateAuthAccount() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldAuthAccount)
	return u
}

// ClearAuthAccount clears the value of the "auth_account" field.
func (u *RelayMonitorUpsert) ClearAuthAccount() *RelayMonitorUpsert {
	u.SetNull(relaymonitor.FieldAuthAccount)
	return u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (u *RelayMonitorUpsert) SetCredentialEncrypted(v string) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldCredentialEncrypted, v)
	return u
}

// UpdateCredentialEncrypted sets the "credential_encrypted" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateCredentialEncrypted() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldCredentialEncrypted)
	return u
}

// ClearCredentialEncrypted clears the value of the "credential_encrypted" field.
func (u *RelayMonitorUpsert) ClearCredentialEncrypted() *RelayMonitorUpsert {
	u.SetNull(relaymonitor.FieldCredentialEncrypted)
	return u
}

// SetWatchedGroups sets the "watched_groups" field.
func (u *RelayMonitorUpsert) SetWatchedGroups(v []string) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldWatchedGroups, v)
	return u
}

// UpdateWatchedGroups sets the "watched_groups" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateWatchedGroups() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldWatchedGroups)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *RelayMonitorUpsert) SetEnabled(v bool) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateEnabled() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldEnabled)
	return u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *RelayMonitorUpsert) SetIntervalSeconds(v int) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldIntervalSeconds, v)
	return u
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateIntervalSeconds() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldIntervalSeconds)
	return u
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *RelayMonitorUpsert) AddIntervalSeconds(v int) *RelayMonitorUpsert {
	u.Add(relaymonitor.FieldIntervalSeconds, v)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *RelayMonitorUpsert) SetLastCheckedAt(v time.Time) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateLastCheckedAt() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *RelayMonitorUpsert) ClearLastCheckedAt() *RelayMonitorUpsert {
	u.SetNull(relaymonitor.FieldLastCheckedAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *RelayMonitorUpsert) SetLastError(v string) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateLastError() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *RelayMonitorUpsert) ClearLastError() *RelayMonitorUpsert {
	u.SetNull(relaymonitor.FieldLastError)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *RelayMonitorUpsert) SetCreatedBy(v int64) *RelayMonitorUpsert {
	u.Set(relaymonitor.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RelayMonitorUpsert) UpdateCreatedBy() *RelayMonitorUpsert {
	u.SetExcluded(relaymonitor.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RelayMonitorUpsert) AddCreatedBy(v int64) *RelayMonitorUpsert {
	u.Add(relaymonitor.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RelayMonitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayMonitorUpsertOne) UpdateNewValues() *RelayMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(relaymonitor.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayMonitor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RelayMonitorUpsertOne) Ignore() *RelayMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayMonitorUpsertOne) DoNothing() *RelayMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayMonitorCreate.OnConflict
// documentation for more info.
func (u *RelayMonitorUpsertOne) Update(set func(*RelayMonitorUpsert)) *RelayMonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayMonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayMonitorUpsertOne) SetUpdatedAt(v time.Time) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateUpdatedAt() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *RelayMonitorUpsertOne) SetName(v string) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateName() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateName()
	})
}

// SetSystem sets the "system" field.
func (u *RelayMonitorUpsertOne) SetSystem(v relaymonitor.System) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateSystem() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateSystem()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *RelayMonitorUpsertOne) SetBaseURL(v string) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateBaseURL() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateBaseURL()
	})
}

// SetVendor sets the "vendor" field.
func (u *RelayMonitorUpsertOne) SetVendor(v string) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateVendor() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateVendor()
	})
}

// ClearVendor clears the value of the "vendor" field.
func (u *RelayMonitorUpsertOne) ClearVendor() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearVendor()
	})
}

// SetAuthAccount sets the "auth_account" field.
func (u *RelayMonitorUpsertOne) SetAuthAccount(v string) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetAuthAccount(v)
	})
}

// UpdateAuthAccount sets the "auth_account" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateAuthAccount() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateAuthAccount()
	})
}

// ClearAuthAccount clears the value of the "auth_account" field.
func (u *RelayMonitorUpsertOne) ClearAuthAccount() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearAuthAccount()
	})
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (u *RelayMonitorUpsertOne) SetCredentialEncrypted(v string) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetCredentialEncrypted(v)
	})
}

// UpdateCredentialEncrypted sets the "credential_encrypted" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateCredentialEncrypted() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateCredentialEncrypted()
	})
}

// ClearCredentialEncrypted clears the value of the "credential_encrypted" field.
func (u *RelayMonitorUpsertOne) ClearCredentialEncrypted() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearCredentialEncrypted()
	})
}

// SetWatchedGroups sets the "watched_groups" field.
func (u *RelayMonitorUpsertOne) SetWatchedGroups(v []string) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetWatchedGroups(v)
	})
}

// UpdateWatchedGroups sets the "watched_groups" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateWatchedGroups() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateWatchedGroups()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RelayMonitorUpsertOne) SetEnabled(v bool) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateEnabled() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateEnabled()
	})
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *RelayMonitorUpsertOne) SetIntervalSeconds(v int) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetIntervalSeconds(v)
	})
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *RelayMonitorUpsertOne) AddIntervalSeconds(v int) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.AddIntervalSeconds(v)
	})
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateIntervalSeconds() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateIntervalSeconds()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *RelayMonitorUpsertOne) SetLastCheckedAt(v time.Time) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateLastCheckedAt() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *RelayMonitorUpsertOne) ClearLastCheckedAt() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *RelayMonitorUpsertOne) SetLastError(v string) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateLastError() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *RelayMonitorUpsertOne) ClearLastError() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearLastError()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RelayMonitorUpsertOne) SetCreatedBy(v int64) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RelayMonitorUpsertOne) AddCreatedBy(v int64) *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RelayMonitorUpsertOne) UpdateCreatedBy() *RelayMonitorUpsertOne {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *RelayMonitorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayMonitorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayMonitorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RelayMonitorUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RelayMonitorUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RelayMonitorCreateBulk is the builder for creating many RelayMonitor entities in bulk.
type RelayMonitorCreateBulk struct {
	config
	err      error
	builders []*RelayMonitorCreate
	conflict []sql.ConflictOption
}

// Save creates the RelayMonitor entities in the database.
func (_c *RelayMonitorCreateBulk) Save(ctx context.Context) ([]*RelayMonitor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelayMonitor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelayMonitorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelayMonitorCreateBulk) SaveX(ctx context.Context) []*RelayMonitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayMonitorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayMonitorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayMonitor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayMonitorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayMonitorCreateBulk) OnConflict(opts ...sql.ConflictOption) *RelayMonitorUpsertBulk {
	_c.conflict = opts
	return &RelayMonitorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayMonitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayMonitorCreateBulk) OnConflictColumns(columns ...string) *RelayMonitorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayMonitorUpsertBulk{
		create: _c,
	}
}

// RelayMonitorUpsertBulk is the builder for "upsert"-ing
// a bulk of RelayMonitor nodes.
type RelayMonitorUpsertBulk struct {
	create *RelayMonitorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RelayMonitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayMonitorUpsertBulk) UpdateNewValues() *RelayMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(relaymonitor.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayMonitor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RelayMonitorUpsertBulk) Ignore() *RelayMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayMonitorUpsertBulk) DoNothing() *RelayMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayMonitorCreateBulk.OnConflict
// documentation for more info.
func (u *RelayMonitorUpsertBulk) Update(set func(*RelayMonitorUpsert)) *RelayMonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayMonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayMonitorUpsertBulk) SetUpdatedAt(v time.Time) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateUpdatedAt() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *RelayMonitorUpsertBulk) SetName(v string) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateName() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateName()
	})
}

// SetSystem sets the "system" field.
func (u *RelayMonitorUpsertBulk) SetSystem(v relaymonitor.System) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateSystem() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateSystem()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *RelayMonitorUpsertBulk) SetBaseURL(v string) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateBaseURL() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateBaseURL()
	})
}

// SetVendor sets the "vendor" field.
func (u *RelayMonitorUpsertBulk) SetVendor(v string) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateVendor() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateVendor()
	})
}

// ClearVendor clears the value of the "vendor" field.
func (u *RelayMonitorUpsertBulk) ClearVendor() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearVendor()
	})
}

// SetAuthAccount sets the "auth_account" field.
func (u *RelayMonitorUpsertBulk) SetAuthAccount(v string) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetAuthAccount(v)
	})
}

// UpdateAuthAccount sets the "auth_account" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateAuthAccount() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateAuthAccount()
	})
}

// ClearAuthAccount clears the value of the "auth_account" field.
func (u *RelayMonitorUpsertBulk) ClearAuthAccount() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearAuthAccount()
	})
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (u *RelayMonitorUpsertBulk) SetCredentialEncrypted(v string) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetCredentialEncrypted(v)
	})
}

// UpdateCredentialEncrypted sets the "credential_encrypted" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateCredentialEncrypted() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateCredentialEncrypted()
	})
}

// ClearCredentialEncrypted clears the value of the "credential_encrypted" field.
func (u *RelayMonitorUpsertBulk) ClearCredentialEncrypted() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearCredentialEncrypted()
	})
}

// SetWatchedGroups sets the "watched_groups" field.
func (u *RelayMonitorUpsertBulk) SetWatchedGroups(v []string) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetWatchedGroups(v)
	})
}

// UpdateWatchedGroups sets the "watched_groups" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateWatchedGroups() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateWatchedGroups()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RelayMonitorUpsertBulk) SetEnabled(v bool) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateEnabled() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateEnabled()
	})
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *RelayMonitorUpsertBulk) SetIntervalSeconds(v int) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetIntervalSeconds(v)
	})
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *RelayMonitorUpsertBulk) AddIntervalSeconds(v int) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.AddIntervalSeconds(v)
	})
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateIntervalSeconds() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateIntervalSeconds()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *RelayMonitorUpsertBulk) SetLastCheckedAt(v time.Time) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateLastCheckedAt() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *RelayMonitorUpsertBulk) ClearLastCheckedAt() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *RelayMonitorUpsertBulk) SetLastError(v string) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateLastError() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *RelayMonitorUpsertBulk) ClearLastError() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.ClearLastError()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RelayMonitorUpsertBulk) SetCreatedBy(v int64) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RelayMonitorUpsertBulk) AddCreatedBy(v int64) *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RelayMonitorUpsertBulk) UpdateCreatedBy() *RelayMonitorUpsertBulk {
	return u.Update(func(s *RelayMonitorUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *RelayMonitorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RelayMonitorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayMonitorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayMonitorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
