// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratesnapshot"
)

// RelayRateSnapshotUpdate is the builder for updating RelayRateSnapshot entities.
type RelayRateSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *RelayRateSnapshotMutation
}

// Where appends a list predicates to the RelayRateSnapshotUpdate builder.
func (_u *RelayRateSnapshotUpdate) Where(ps ...predicate.RelayRateSnapshot) *RelayRateSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMonitorID sets the "monitor_id" field.
func (_u *RelayRateSnapshotUpdate) SetMonitorID(v int64) *RelayRateSnapshotUpdate {
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdate) SetNillableMonitorID(v *int64) *RelayRateSnapshotUpdate {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *RelayRateSnapshotUpdate) SetGroupName(v string) *RelayRateSnapshotUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdate) SetNillableGroupName(v *string) *RelayRateSnapshotUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *RelayRateSnapshotUpdate) SetRate(v float64) *RelayRateSnapshotUpdate {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdate) SetNillableRate(v *float64) *RelayRateSnapshotUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *RelayRateSnapshotUpdate) AddRate(v float64) *RelayRateSnapshotUpdate {
	_u.mutation.AddRate(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayRateSnapshotUpdate) SetUpdatedAt(v time.Time) *RelayRateSnapshotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdate) SetNillableUpdatedAt(v *time.Time) *RelayRateSnapshotUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetMonitor sets the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateSnapshotUpdate) SetMonitor(v *RelayMonitor) *RelayRateSnapshotUpdate {
	return _u.SetMonitorID(v.ID)
}

// Mutation returns the RelayRateSnapshotMutation object of the builder.
func (_u *RelayRateSnapshotUpdate) Mutation() *RelayRateSnapshotMutation {
	return _u.mutation
}

// ClearMonitor clears the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateSnapshotUpdate) ClearMonitor() *RelayRateSnapshotUpdate {
	_u.mutation.ClearMonitor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelayRateSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayRateSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelayRateSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayRateSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayRateSnapshotUpdate) check() error {
	if v, ok := _u.mutation.GroupName(); ok {
		if err := relayratesnapshot.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "RelayRateSnapshot.group_name": %w`, err)}
		}
	}
	if _u.mutation.MonitorCleared() && len(_u.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayRateSnapshot.monitor"`)
	}
	return nil
}

func (_u *RelayRateSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relayratesnapshot.Table, relayratesnapshot.Columns, sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(relayratesnapshot.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(relayratesnapshot.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(relayratesnapshot.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relayratesnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratesnapshot.MonitorTable,
			Columns: []string{relayratesnapshot.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratesnapshot.MonitorTable,
			Columns: []string{relayratesnapshot.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relayratesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelayRateSnapshotUpdateOne is the builder for updating a single RelayRateSnapshot entity.
type RelayRateSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelayRateSnapshotMutation
}

// SetMonitorID sets the "monitor_id" field.
func (_u *RelayRateSnapshotUpdateOne) SetMonitorID(v int64) *RelayRateSnapshotUpdateOne {
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdateOne) SetNillableMonitorID(v *int64) *RelayRateSnapshotUpdateOne {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *RelayRateSnapshotUpdateOne) SetGroupName(v string) *RelayRateSnapshotUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdateOne) SetNillableGroupName(v *string) *RelayRateSnapshotUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *RelayRateSnapshotUpdateOne) SetRate(v float64) *RelayRateSnapshotUpdateOne {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdateOne) SetNillableRate(v *float64) *RelayRateSnapshotUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *RelayRateSnapshotUpdateOne) AddRate(v float64) *RelayRateSnapshotUpdateOne {
	_u.mutation.AddRate(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayRateSnapshotUpdateOne) SetUpdatedAt(v time.Time) *RelayRateSnapshotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RelayRateSnapshotUpdateOne) SetNillableUpdatedAt(v *time.Time) *RelayRateSnapshotUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetMonitor sets the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateSnapshotUpdateOne) SetMonitor(v *RelayMonitor) *RelayRateSnapshotUpdateOne {
	return _u.SetMonitorID(v.ID)
}

// Mutation returns the RelayRateSnapshotMutation object of the builder.
func (_u *RelayRateSnapshotUpdateOne) Mutation() *RelayRateSnapshotMutation {
	return _u.mutation
}

// ClearMonitor clears the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateSnapshotUpdateOne) ClearMonitor() *RelayRateSnapshotUpdateOne {
	_u.mutation.ClearMonitor()
	return _u
}

// Where appends a list predicates to the RelayRateSnapshotUpdate builder.
func (_u *RelayRateSnapshotUpdateOne) Where(ps ...predicate.RelayRateSnapshot) *RelayRateSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelayRateSnapshotUpdateOne) Select(field string, fields ...string) *RelayRateSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelayRateSnapshot entity.
func (_u *RelayRateSnapshotUpdateOne) Save(ctx context.Context) (*RelayRateSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayRateSnapshotUpdateOne) SaveX(ctx context.Context) *RelayRateSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelayRateSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayRateSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayRateSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.GroupName(); ok {
		if err := relayratesnapshot.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "RelayRateSnapshot.group_name": %w`, err)}
		}
	}
	if _u.mutation.MonitorCleared() && len(_u.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayRateSnapshot.monitor"`)
	}
	return nil
}

func (_u *RelayRateSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *RelayRateSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relayratesnapshot.Table, relayratesnapshot.Columns, sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelayRateSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relayratesnapshot.FieldID)
		for _, f := range fields {
			if !relayratesnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relayratesnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(relayratesnapshot.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(relayratesnapshot.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(relayratesnapshot.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relayratesnapshot.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratesnapshot.MonitorTable,
			Columns: []string{relayratesnapshot.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratesnapshot.MonitorTable,
			Columns: []string{relayratesnapshot.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RelayRateSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relayratesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
