// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratesnapshot"
)

// RelayRateSnapshot is the model entity for the RelayRateSnapshot schema.
type RelayRateSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID int64 `json:"monitor_id,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName string `json:"group_name,omitempty"`
	// 当前分组倍率
	Rate float64 `json:"rate,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayRateSnapshotQuery when eager-loading is set.
	Edges        RelayRateSnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayRateSnapshotEdges holds the relations/edges for other nodes in the graph.
type RelayRateSnapshotEdges struct {
	// Monitor holds the value of the monitor edge.
	Monitor *RelayMonitor `json:"monitor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MonitorOrErr returns the Monitor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayRateSnapshotEdges) MonitorOrErr() (*RelayMonitor, error) {
	if e.Monitor != nil {
		return e.Monitor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: relaymonitor.Label}
	}
	return nil, &NotLoadedError{edge: "monitor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayRateSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relayratesnapshot.FieldRate:
			values[i] = new(sql.NullFloat64)
		case relayratesnapshot.FieldID, relayratesnapshot.FieldMonitorID:
			values[i] = new(sql.NullInt64)
		case relayratesnapshot.FieldGroupName:
			values[i] = new(sql.NullString)
		case relayratesnapshot.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayRateSnapshot fields.
func (_m *RelayRateSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relayratesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case relayratesnapshot.FieldMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value.Valid {
				_m.MonitorID = value.Int64
			}
		case relayratesnapshot.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = value.String
			}
		case relayratesnapshot.FieldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = value.Float64
			}
		case relayratesnapshot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayRateSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *RelayRateSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMonitor queries the "monitor" edge of the RelayRateSnapshot entity.
func (_m *RelayRateSnapshot) QueryMonitor() *RelayMonitorQuery {
	return NewRelayRateSnapshotClient(_m.config).QueryMonitor(_m)
}

// Update returns a builder for updating this RelayRateSnapshot.
// Note that you need to call RelayRateSnapshot.Unwrap() before calling this method if this RelayRateSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayRateSnapshot) Update() *RelayRateSnapshotUpdateOne {
	return NewRelayRateSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayRateSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayRateSnapshot) Unwrap() *RelayRateSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayRateSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayRateSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("RelayRateSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("group_name=")
	builder.WriteString(_m.GroupName)
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rate))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RelayRateSnapshots is a parsable slice of RelayRateSnapshot.
type RelayRateSnapshots []*RelayRateSnapshot
