// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratechange"
)

// RelayRateChange is the model entity for the RelayRateChange schema.
type RelayRateChange struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID int64 `json:"monitor_id,omitempty"`
	// 监控名称快照，便于历史独立展示
	Site string `json:"site,omitempty"`
	// System holds the value of the "system" field.
	System string `json:"system,omitempty"`
	// Vendor holds the value of the "vendor" field.
	Vendor string `json:"vendor,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName string `json:"group_name,omitempty"`
	// OldRate holds the value of the "old_rate" field.
	OldRate float64 `json:"old_rate,omitempty"`
	// NewRate holds the value of the "new_rate" field.
	NewRate float64 `json:"new_rate,omitempty"`
	// up=涨(倍率变大), down=跌(倍率变小)
	Direction relayratechange.Direction `json:"direction,omitempty"`
	// 公告文本，如 分组倍率从 0.005x 变为 0.001x
	Content string `json:"content,omitempty"`
	// DetectedAt holds the value of the "detected_at" field.
	DetectedAt time.Time `json:"detected_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayRateChangeQuery when eager-loading is set.
	Edges        RelayRateChangeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayRateChangeEdges holds the relations/edges for other nodes in the graph.
type RelayRateChangeEdges struct {
	// Monitor holds the value of the monitor edge.
	Monitor *RelayMonitor `json:"monitor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MonitorOrErr returns the Monitor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RelayRateChangeEdges) MonitorOrErr() (*RelayMonitor, error) {
	if e.Monitor != nil {
		return e.Monitor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: relaymonitor.Label}
	}
	return nil, &NotLoadedError{edge: "monitor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayRateChange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relayratechange.FieldOldRate, relayratechange.FieldNewRate:
			values[i] = new(sql.NullFloat64)
		case relayratechange.FieldID, relayratechange.FieldMonitorID:
			values[i] = new(sql.NullInt64)
		case relayratechange.FieldSite, relayratechange.FieldSystem, relayratechange.FieldVendor, relayratechange.FieldGroupName, relayratechange.FieldDirection, relayratechange.FieldContent:
			values[i] = new(sql.NullString)
		case relayratechange.FieldDetectedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayRateChange fields.
func (_m *RelayRateChange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relayratechange.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case relayratechange.FieldMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value.Valid {
				_m.MonitorID = value.Int64
			}
		case relayratechange.FieldSite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site", values[i])
			} else if value.Valid {
				_m.Site = value.String
			}
		case relayratechange.FieldSystem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system", values[i])
			} else if value.Valid {
				_m.System = value.String
			}
		case relayratechange.FieldVendor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vendor", values[i])
			} else if value.Valid {
				_m.Vendor = value.String
			}
		case relayratechange.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = value.String
			}
		case relayratechange.FieldOldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field old_rate", values[i])
			} else if value.Valid {
				_m.OldRate = value.Float64
			}
		case relayratechange.FieldNewRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field new_rate", values[i])
			} else if value.Valid {
				_m.NewRate = value.Float64
			}
		case relayratechange.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				_m.Direction = relayratechange.Direction(value.String)
			}
		case relayratechange.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case relayratechange.FieldDetectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field detected_at", values[i])
			} else if value.Valid {
				_m.DetectedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayRateChange.
// This includes values selected through modifiers, order, etc.
func (_m *RelayRateChange) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMonitor queries the "monitor" edge of the RelayRateChange entity.
func (_m *RelayRateChange) QueryMonitor() *RelayMonitorQuery {
	return NewRelayRateChangeClient(_m.config).QueryMonitor(_m)
}

// Update returns a builder for updating this RelayRateChange.
// Note that you need to call RelayRateChange.Unwrap() before calling this method if this RelayRateChange
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayRateChange) Update() *RelayRateChangeUpdateOne {
	return NewRelayRateChangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayRateChange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayRateChange) Unwrap() *RelayRateChange {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayRateChange is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayRateChange) String() string {
	var builder strings.Builder
	builder.WriteString("RelayRateChange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("site=")
	builder.WriteString(_m.Site)
	builder.WriteString(", ")
	builder.WriteString("system=")
	builder.WriteString(_m.System)
	builder.WriteString(", ")
	builder.WriteString("vendor=")
	builder.WriteString(_m.Vendor)
	builder.WriteString(", ")
	builder.WriteString("group_name=")
	builder.WriteString(_m.GroupName)
	builder.WriteString(", ")
	builder.WriteString("old_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.OldRate))
	builder.WriteString(", ")
	builder.WriteString("new_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.NewRate))
	builder.WriteString(", ")
	builder.WriteString("direction=")
	builder.WriteString(fmt.Sprintf("%v", _m.Direction))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("detected_at=")
	builder.WriteString(_m.DetectedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RelayRateChanges is a parsable slice of RelayRateChange.
type RelayRateChanges []*RelayRateChange
