// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratesnapshot"
)

// RelayRateSnapshotCreate is the builder for creating a RelayRateSnapshot entity.
type RelayRateSnapshotCreate struct {
	config
	mutation *RelayRateSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMonitorID sets the "monitor_id" field.
func (_c *RelayRateSnapshotCreate) SetMonitorID(v int64) *RelayRateSnapshotCreate {
	_c.mutation.SetMonitorID(v)
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *RelayRateSnapshotCreate) SetGroupName(v string) *RelayRateSnapshotCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetRate sets the "rate" field.
func (_c *RelayRateSnapshotCreate) SetRate(v float64) *RelayRateSnapshotCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RelayRateSnapshotCreate) SetUpdatedAt(v time.Time) *RelayRateSnapshotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RelayRateSnapshotCreate) SetNillableUpdatedAt(v *time.Time) *RelayRateSnapshotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMonitor sets the "monitor" edge to the RelayMonitor entity.
func (_c *RelayRateSnapshotCreate) SetMonitor(v *RelayMonitor) *RelayRateSnapshotCreate {
	return _c.SetMonitorID(v.ID)
}

// Mutation returns the RelayRateSnapshotMutation object of the builder.
func (_c *RelayRateSnapshotCreate) Mutation() *RelayRateSnapshotMutation {
	return _c.mutation
}

// Save creates the RelayRateSnapshot in the database.
func (_c *RelayRateSnapshotCreate) Save(ctx context.Context) (*RelayRateSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelayRateSnapshotCreate) SaveX(ctx context.Context) *RelayRateSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayRateSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayRateSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelayRateSnapshotCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := relayratesnapshot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelayRateSnapshotCreate) check() error {
	if _, ok := _c.mutation.MonitorID(); !ok {
		return &ValidationError{Name: "monitor_id", err: errors.New(`ent: missing required field "RelayRateSnapshot.monitor_id"`)}
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "RelayRateSnapshot.group_name"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := relayratesnapshot.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "RelayRateSnapshot.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "RelayRateSnapshot.rate"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RelayRateSnapshot.updated_at"`)}
	}
	if len(_c.mutation.MonitorIDs()) == 0 {
		return &ValidationError{Name: "monitor", err: errors.New(`ent: missing required edge "RelayRateSnapshot.monitor"`)}
	}
	return nil
}

func (_c *RelayRateSnapshotCreate) sqlSave(ctx context.Context) (*RelayRateSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelayRateSnapshotCreate) createSpec() (*RelayRateSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &RelayRateSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relayratesnapshot.Table, sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(relayratesnapshot.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(relayratesnapshot.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(relayratesnapshot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratesnapshot.MonitorTable,
			Columns: []string{relayratesnapshot.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MonitorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayRateSnapshot.Create().
//		SetMonitorID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayRateSnapshotUpsert) {
//			SetMonitorID(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayRateSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *RelayRateSnapshotUpsertOne {
	_c.conflict = opts
	return &RelayRateSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayRateSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayRateSnapshotCreate) OnConflictColumns(columns ...string) *RelayRateSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayRateSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// RelayRateSnapshotUpsertOne is the builder for "upsert"-ing
	//  one RelayRateSnapshot node.
	RelayRateSnapshotUpsertOne struct {
		create *RelayRateSnapshotCreate
	}

	// RelayRateSnapshotUpsert is the "OnConflict" setter.
	RelayRateSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetMonitorID sets the "monitor_id" field.
func (u *RelayRateSnapshotUpsert) SetMonitorID(v int64) *RelayRateSnapshotUpsert {
	u.Set(relayratesnapshot.FieldMonitorID, v)
	return u
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsert) UpdateMonitorID() *RelayRateSnapshotUpsert {
	u.SetExcluded(relayratesnapshot.FieldMonitorID)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *RelayRateSnapshotUpsert) SetGroupName(v string) *RelayRateSnapshotUpsert {
	u.Set(relayratesnapshot.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsert) UpdateGroupName() *RelayRateSnapshotUpsert {
	u.SetExcluded(relayratesnapshot.FieldGroupName)
	return u
}

// SetRate sets the "rate" field.
func (u *RelayRateSnapshotUpsert) SetRate(v float64) *RelayRateSnapshotUpsert {
	u.Set(relayratesnapshot.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsert) UpdateRate() *RelayRateSnapshotUpsert {
	u.SetExcluded(relayratesnapshot.FieldRate)
	return u
}

// AddRate adds v to the "rate" field.
func (u *RelayRateSnapshotUpsert) AddRate(v float64) *RelayRateSnapshotUpsert {
	u.Add(relayratesnapshot.FieldRate, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayRateSnapshotUpsert) SetUpdatedAt(v time.Time) *RelayRateSnapshotUpsert {
	u.Set(relayratesnapshot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsert) UpdateUpdatedAt() *RelayRateSnapshotUpsert {
	u.SetExcluded(relayratesnapshot.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RelayRateSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayRateSnapshotUpsertOne) UpdateNewValues() *RelayRateSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayRateSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RelayRateSnapshotUpsertOne) Ignore() *RelayRateSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayRateSnapshotUpsertOne) DoNothing() *RelayRateSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayRateSnapshotCreate.OnConflict
// documentation for more info.
func (u *RelayRateSnapshotUpsertOne) Update(set func(*RelayRateSnapshotUpsert)) *RelayRateSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayRateSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetMonitorID sets the "monitor_id" field.
func (u *RelayRateSnapshotUpsertOne) SetMonitorID(v int64) *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertOne) UpdateMonitorID() *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateMonitorID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *RelayRateSnapshotUpsertOne) SetGroupName(v string) *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertOne) UpdateGroupName() *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateGroupName()
	})
}

// SetRate sets the "rate" field.
func (u *RelayRateSnapshotUpsertOne) SetRate(v float64) *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *RelayRateSnapshotUpsertOne) AddRate(v float64) *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertOne) UpdateRate() *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateRate()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayRateSnapshotUpsertOne) SetUpdatedAt(v time.Time) *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertOne) UpdateUpdatedAt() *RelayRateSnapshotUpsertOne {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RelayRateSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayRateSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayRateSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RelayRateSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RelayRateSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RelayRateSnapshotCreateBulk is the builder for creating many RelayRateSnapshot entities in bulk.
type RelayRateSnapshotCreateBulk struct {
	config
	err      error
	builders []*RelayRateSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the RelayRateSnapshot entities in the database.
func (_c *RelayRateSnapshotCreateBulk) Save(ctx context.Context) ([]*RelayRateSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelayRateSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelayRateSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelayRateSnapshotCreateBulk) SaveX(ctx context.Context) []*RelayRateSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayRateSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayRateSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayRateSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayRateSnapshotUpsert) {
//			SetMonitorID(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayRateSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *RelayRateSnapshotUpsertBulk {
	_c.conflict = opts
	return &RelayRateSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayRateSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayRateSnapshotCreateBulk) OnConflictColumns(columns ...string) *RelayRateSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayRateSnapshotUpsertBulk{
		create: _c,
	}
}

// RelayRateSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of RelayRateSnapshot nodes.
type RelayRateSnapshotUpsertBulk struct {
	create *RelayRateSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RelayRateSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayRateSnapshotUpsertBulk) UpdateNewValues() *RelayRateSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayRateSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RelayRateSnapshotUpsertBulk) Ignore() *RelayRateSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayRateSnapshotUpsertBulk) DoNothing() *RelayRateSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayRateSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *RelayRateSnapshotUpsertBulk) Update(set func(*RelayRateSnapshotUpsert)) *RelayRateSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayRateSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetMonitorID sets the "monitor_id" field.
func (u *RelayRateSnapshotUpsertBulk) SetMonitorID(v int64) *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertBulk) UpdateMonitorID() *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateMonitorID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *RelayRateSnapshotUpsertBulk) SetGroupName(v string) *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertBulk) UpdateGroupName() *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateGroupName()
	})
}

// SetRate sets the "rate" field.
func (u *RelayRateSnapshotUpsertBulk) SetRate(v float64) *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *RelayRateSnapshotUpsertBulk) AddRate(v float64) *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertBulk) UpdateRate() *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateRate()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RelayRateSnapshotUpsertBulk) SetUpdatedAt(v time.Time) *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RelayRateSnapshotUpsertBulk) UpdateUpdatedAt() *RelayRateSnapshotUpsertBulk {
	return u.Update(func(s *RelayRateSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RelayRateSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RelayRateSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayRateSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayRateSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
