// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
)

// RelayMonitor is the model entity for the RelayMonitor schema.
type RelayMonitor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 中转站显示名称
	Name string `json:"name,omitempty"`
	// 目标站点使用的网关系统，决定探测解析器
	System relaymonitor.System `json:"system,omitempty"`
	// 中转站站点根地址，如 https://example.com
	BaseURL string `json:"base_url,omitempty"`
	// 厂商标签，如 OpenAI（仅展示用）
	Vendor string `json:"vendor,omitempty"`
	// AES-256-GCM 加密的访问凭证：sub2api 需要 Bearer token，newapi 可留空
	CredentialEncrypted string `json:"-"`
	// 需要监控的分组名列表；为空表示尚未选择，不探测任何分组
	WatchedGroups []string `json:"watched_groups,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// 探测间隔秒数
	IntervalSeconds int `json:"interval_seconds,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// 最近一次探测的错误信息，空表示成功
	LastError string `json:"last_error,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RelayMonitorQuery when eager-loading is set.
	Edges        RelayMonitorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RelayMonitorEdges holds the relations/edges for other nodes in the graph.
type RelayMonitorEdges struct {
	// Snapshots holds the value of the snapshots edge.
	Snapshots []*RelayRateSnapshot `json:"snapshots,omitempty"`
	// Changes holds the value of the changes edge.
	Changes []*RelayRateChange `json:"changes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SnapshotsOrErr returns the Snapshots value or an error if the edge
// was not loaded in eager-loading.
func (e RelayMonitorEdges) SnapshotsOrErr() ([]*RelayRateSnapshot, error) {
	if e.loadedTypes[0] {
		return e.Snapshots, nil
	}
	return nil, &NotLoadedError{edge: "snapshots"}
}

// ChangesOrErr returns the Changes value or an error if the edge
// was not loaded in eager-loading.
func (e RelayMonitorEdges) ChangesOrErr() ([]*RelayRateChange, error) {
	if e.loadedTypes[1] {
		return e.Changes, nil
	}
	return nil, &NotLoadedError{edge: "changes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelayMonitor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relaymonitor.FieldWatchedGroups:
			values[i] = new([]byte)
		case relaymonitor.FieldEnabled:
			values[i] = new(sql.NullBool)
		case relaymonitor.FieldID, relaymonitor.FieldIntervalSeconds, relaymonitor.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case relaymonitor.FieldName, relaymonitor.FieldSystem, relaymonitor.FieldBaseURL, relaymonitor.FieldVendor, relaymonitor.FieldCredentialEncrypted, relaymonitor.FieldLastError:
			values[i] = new(sql.NullString)
		case relaymonitor.FieldCreatedAt, relaymonitor.FieldUpdatedAt, relaymonitor.FieldLastCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelayMonitor fields.
func (_m *RelayMonitor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relaymonitor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case relaymonitor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case relaymonitor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case relaymonitor.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case relaymonitor.FieldSystem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system", values[i])
			} else if value.Valid {
				_m.System = relaymonitor.System(value.String)
			}
		case relaymonitor.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case relaymonitor.FieldVendor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vendor", values[i])
			} else if value.Valid {
				_m.Vendor = value.String
			}
		case relaymonitor.FieldCredentialEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_encrypted", values[i])
			} else if value.Valid {
				_m.CredentialEncrypted = value.String
			}
		case relaymonitor.FieldWatchedGroups:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field watched_groups", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.WatchedGroups); err != nil {
					return fmt.Errorf("unmarshal field watched_groups: %w", err)
				}
			}
		case relaymonitor.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case relaymonitor.FieldIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_seconds", values[i])
			} else if value.Valid {
				_m.IntervalSeconds = int(value.Int64)
			}
		case relaymonitor.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case relaymonitor.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case relaymonitor.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelayMonitor.
// This includes values selected through modifiers, order, etc.
func (_m *RelayMonitor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySnapshots queries the "snapshots" edge of the RelayMonitor entity.
func (_m *RelayMonitor) QuerySnapshots() *RelayRateSnapshotQuery {
	return NewRelayMonitorClient(_m.config).QuerySnapshots(_m)
}

// QueryChanges queries the "changes" edge of the RelayMonitor entity.
func (_m *RelayMonitor) QueryChanges() *RelayRateChangeQuery {
	return NewRelayMonitorClient(_m.config).QueryChanges(_m)
}

// Update returns a builder for updating this RelayMonitor.
// Note that you need to call RelayMonitor.Unwrap() before calling this method if this RelayMonitor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelayMonitor) Update() *RelayMonitorUpdateOne {
	return NewRelayMonitorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelayMonitor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelayMonitor) Unwrap() *RelayMonitor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelayMonitor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelayMonitor) String() string {
	var builder strings.Builder
	builder.WriteString("RelayMonitor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("system=")
	builder.WriteString(fmt.Sprintf("%v", _m.System))
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("vendor=")
	builder.WriteString(_m.Vendor)
	builder.WriteString(", ")
	builder.WriteString("credential_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("watched_groups=")
	builder.WriteString(fmt.Sprintf("%v", _m.WatchedGroups))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalSeconds))
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// RelayMonitors is a parsable slice of RelayMonitor.
type RelayMonitors []*RelayMonitor
