// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratechange"
	"github.com/Wei-Shaw/sub2api/ent/relayratesnapshot"
)

// RelayMonitorQuery is the builder for querying RelayMonitor entities.
type RelayMonitorQuery struct {
	config
	ctx           *QueryContext
	order         []relaymonitor.OrderOption
	inters        []Interceptor
	predicates    []predicate.RelayMonitor
	withSnapshots *RelayRateSnapshotQuery
	withChanges   *RelayRateChangeQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RelayMonitorQuery builder.
func (_q *RelayMonitorQuery) Where(ps ...predicate.RelayMonitor) *RelayMonitorQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RelayMonitorQuery) Limit(limit int) *RelayMonitorQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RelayMonitorQuery) Offset(offset int) *RelayMonitorQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RelayMonitorQuery) Unique(unique bool) *RelayMonitorQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RelayMonitorQuery) Order(o ...relaymonitor.OrderOption) *RelayMonitorQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySnapshots chains the current query on the "snapshots" edge.
func (_q *RelayMonitorQuery) QuerySnapshots() *RelayRateSnapshotQuery {
	query := (&RelayRateSnapshotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaymonitor.Table, relaymonitor.FieldID, selector),
			sqlgraph.To(relayratesnapshot.Table, relayratesnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, relaymonitor.SnapshotsTable, relaymonitor.SnapshotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChanges chains the current query on the "changes" edge.
func (_q *RelayMonitorQuery) QueryChanges() *RelayRateChangeQuery {
	query := (&RelayRateChangeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(relaymonitor.Table, relaymonitor.FieldID, selector),
			sqlgraph.To(relayratechange.Table, relayratechange.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, relaymonitor.ChangesTable, relaymonitor.ChangesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RelayMonitor entity from the query.
// Returns a *NotFoundError when no RelayMonitor was found.
func (_q *RelayMonitorQuery) First(ctx context.Context) (*RelayMonitor, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{relaymonitor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RelayMonitorQuery) FirstX(ctx context.Context) *RelayMonitor {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RelayMonitor ID from the query.
// Returns a *NotFoundError when no RelayMonitor ID was found.
func (_q *RelayMonitorQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{relaymonitor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RelayMonitorQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RelayMonitor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RelayMonitor entity is found.
// Returns a *NotFoundError when no RelayMonitor entities are found.
func (_q *RelayMonitorQuery) Only(ctx context.Context) (*RelayMonitor, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{relaymonitor.Label}
	default:
		return nil, &NotSingularError{relaymonitor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RelayMonitorQuery) OnlyX(ctx context.Context) *RelayMonitor {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RelayMonitor ID in the query.
// Returns a *NotSingularError when more than one RelayMonitor ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RelayMonitorQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{relaymonitor.Label}
	default:
		err = &NotSingularError{relaymonitor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RelayMonitorQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RelayMonitors.
func (_q *RelayMonitorQuery) All(ctx context.Context) ([]*RelayMonitor, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RelayMonitor, *RelayMonitorQuery]()
	return withInterceptors[[]*RelayMonitor](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RelayMonitorQuery) AllX(ctx context.Context) []*RelayMonitor {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RelayMonitor IDs.
func (_q *RelayMonitorQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(relaymonitor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RelayMonitorQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RelayMonitorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RelayMonitorQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RelayMonitorQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RelayMonitorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RelayMonitorQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RelayMonitorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RelayMonitorQuery) Clone() *RelayMonitorQuery {
	if _q == nil {
		return nil
	}
	return &RelayMonitorQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]relaymonitor.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.RelayMonitor{}, _q.predicates...),
		withSnapshots: _q.withSnapshots.Clone(),
		withChanges:   _q.withChanges.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSnapshots tells the query-builder to eager-load the nodes that are connected to
// the "snapshots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayMonitorQuery) WithSnapshots(opts ...func(*RelayRateSnapshotQuery)) *RelayMonitorQuery {
	query := (&RelayRateSnapshotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSnapshots = query
	return _q
}

// WithChanges tells the query-builder to eager-load the nodes that are connected to
// the "changes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RelayMonitorQuery) WithChanges(opts ...func(*RelayRateChangeQuery)) *RelayMonitorQuery {
	query := (&RelayRateChangeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChanges = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RelayMonitor.Query().
//		GroupBy(relaymonitor.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RelayMonitorQuery) GroupBy(field string, fields ...string) *RelayMonitorGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RelayMonitorGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = relaymonitor.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.RelayMonitor.Query().
//		Select(relaymonitor.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *RelayMonitorQuery) Select(fields ...string) *RelayMonitorSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RelayMonitorSelect{RelayMonitorQuery: _q}
	sbuild.label = relaymonitor.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RelayMonitorSelect configured with the given aggregations.
func (_q *RelayMonitorQuery) Aggregate(fns ...AggregateFunc) *RelayMonitorSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RelayMonitorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !relaymonitor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RelayMonitorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RelayMonitor, error) {
	var (
		nodes       = []*RelayMonitor{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSnapshots != nil,
			_q.withChanges != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RelayMonitor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RelayMonitor{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSnapshots; query != nil {
		if err := _q.loadSnapshots(ctx, query, nodes,
			func(n *RelayMonitor) { n.Edges.Snapshots = []*RelayRateSnapshot{} },
			func(n *RelayMonitor, e *RelayRateSnapshot) { n.Edges.Snapshots = append(n.Edges.Snapshots, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChanges; query != nil {
		if err := _q.loadChanges(ctx, query, nodes,
			func(n *RelayMonitor) { n.Edges.Changes = []*RelayRateChange{} },
			func(n *RelayMonitor, e *RelayRateChange) { n.Edges.Changes = append(n.Edges.Changes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RelayMonitorQuery) loadSnapshots(ctx context.Context, query *RelayRateSnapshotQuery, nodes []*RelayMonitor, init func(*RelayMonitor), assign func(*RelayMonitor, *RelayRateSnapshot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RelayMonitor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(relayratesnapshot.FieldMonitorID)
	}
	query.Where(predicate.RelayRateSnapshot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(relaymonitor.SnapshotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MonitorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "monitor_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RelayMonitorQuery) loadChanges(ctx context.Context, query *RelayRateChangeQuery, nodes []*RelayMonitor, init func(*RelayMonitor), assign func(*RelayMonitor, *RelayRateChange)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RelayMonitor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(relayratechange.FieldMonitorID)
	}
	query.Where(predicate.RelayRateChange(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(relaymonitor.ChangesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MonitorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "monitor_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RelayMonitorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RelayMonitorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(relaymonitor.Table, relaymonitor.Columns, sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaymonitor.FieldID)
		for i := range fields {
			if fields[i] != relaymonitor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RelayMonitorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(relaymonitor.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = relaymonitor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RelayMonitorQuery) ForUpdate(opts ...sql.LockOption) *RelayMonitorQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RelayMonitorQuery) ForShare(opts ...sql.LockOption) *RelayMonitorQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RelayMonitorGroupBy is the group-by builder for RelayMonitor entities.
type RelayMonitorGroupBy struct {
	selector
	build *RelayMonitorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RelayMonitorGroupBy) Aggregate(fns ...AggregateFunc) *RelayMonitorGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RelayMonitorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelayMonitorQuery, *RelayMonitorGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RelayMonitorGroupBy) sqlScan(ctx context.Context, root *RelayMonitorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RelayMonitorSelect is the builder for selecting fields of RelayMonitor entities.
type RelayMonitorSelect struct {
	*RelayMonitorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RelayMonitorSelect) Aggregate(fns ...AggregateFunc) *RelayMonitorSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RelayMonitorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RelayMonitorQuery, *RelayMonitorSelect](ctx, _s.RelayMonitorQuery, _s, _s.inters, v)
}

func (_s *RelayMonitorSelect) sqlScan(ctx context.Context, root *RelayMonitorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
