// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratechange"
	"github.com/Wei-Shaw/sub2api/ent/relayratesnapshot"
)

// RelayMonitorUpdate is the builder for updating RelayMonitor entities.
type RelayMonitorUpdate struct {
	config
	hooks    []Hook
	mutation *RelayMonitorMutation
}

// Where appends a list predicates to the RelayMonitorUpdate builder.
func (_u *RelayMonitorUpdate) Where(ps ...predicate.RelayMonitor) *RelayMonitorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayMonitorUpdate) SetUpdatedAt(v time.Time) *RelayMonitorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RelayMonitorUpdate) SetName(v string) *RelayMonitorUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableName(v *string) *RelayMonitorUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSystem sets the "system" field.
func (_u *RelayMonitorUpdate) SetSystem(v relaymonitor.System) *RelayMonitorUpdate {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableSystem(v *relaymonitor.System) *RelayMonitorUpdate {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *RelayMonitorUpdate) SetBaseURL(v string) *RelayMonitorUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableBaseURL(v *string) *RelayMonitorUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *RelayMonitorUpdate) SetVendor(v string) *RelayMonitorUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableVendor(v *string) *RelayMonitorUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// ClearVendor clears the value of the "vendor" field.
func (_u *RelayMonitorUpdate) ClearVendor() *RelayMonitorUpdate {
	_u.mutation.ClearVendor()
	return _u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_u *RelayMonitorUpdate) SetCredentialEncrypted(v string) *RelayMonitorUpdate {
	_u.mutation.SetCredentialEncrypted(v)
	return _u
}

// SetNillableCredentialEncrypted sets the "credential_encrypted" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableCredentialEncrypted(v *string) *RelayMonitorUpdate {
	if v != nil {
		_u.SetCredentialEncrypted(*v)
	}
	return _u
}

// ClearCredentialEncrypted clears the value of the "credential_encrypted" field.
func (_u *RelayMonitorUpdate) ClearCredentialEncrypted() *RelayMonitorUpdate {
	_u.mutation.ClearCredentialEncrypted()
	return _u
}

// SetWatchedGroups sets the "watched_groups" field.
func (_u *RelayMonitorUpdate) SetWatchedGroups(v []string) *RelayMonitorUpdate {
	_u.mutation.SetWatchedGroups(v)
	return _u
}

// AppendWatchedGroups appends value to the "watched_groups" field.
func (_u *RelayMonitorUpdate) AppendWatchedGroups(v []string) *RelayMonitorUpdate {
	_u.mutation.AppendWatchedGroups(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RelayMonitorUpdate) SetEnabled(v bool) *RelayMonitorUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableEnabled(v *bool) *RelayMonitorUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *RelayMonitorUpdate) SetIntervalSeconds(v int) *RelayMonitorUpdate {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableIntervalSeconds(v *int) *RelayMonitorUpdate {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *RelayMonitorUpdate) AddIntervalSeconds(v int) *RelayMonitorUpdate {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *RelayMonitorUpdate) SetLastCheckedAt(v time.Time) *RelayMonitorUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableLastCheckedAt(v *time.Time) *RelayMonitorUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *RelayMonitorUpdate) ClearLastCheckedAt() *RelayMonitorUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *RelayMonitorUpdate) SetLastError(v string) *RelayMonitorUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableLastError(v *string) *RelayMonitorUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *RelayMonitorUpdate) ClearLastError() *RelayMonitorUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RelayMonitorUpdate) SetCreatedBy(v int64) *RelayMonitorUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RelayMonitorUpdate) SetNillableCreatedBy(v *int64) *RelayMonitorUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RelayMonitorUpdate) AddCreatedBy(v int64) *RelayMonitorUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddSnapshotIDs adds the "snapshots" edge to the RelayRateSnapshot entity by IDs.
func (_u *RelayMonitorUpdate) AddSnapshotIDs(ids ...int64) *RelayMonitorUpdate {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the RelayRateSnapshot entity.
func (_u *RelayMonitorUpdate) AddSnapshots(v ...*RelayRateSnapshot) *RelayMonitorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the RelayRateChange entity by IDs.
func (_u *RelayMonitorUpdate) AddChangeIDs(ids ...int64) *RelayMonitorUpdate {
	_u.mutation.AddChangeIDs(ids...)
	return _u
}

// AddChanges adds the "changes" edges to the RelayRateChange entity.
func (_u *RelayMonitorUpdate) AddChanges(v ...*RelayRateChange) *RelayMonitorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeIDs(ids...)
}

// Mutation returns the RelayMonitorMutation object of the builder.
func (_u *RelayMonitorUpdate) Mutation() *RelayMonitorMutation {
	return _u.mutation
}

// ClearSnapshots clears all "snapshots" edges to the RelayRateSnapshot entity.
func (_u *RelayMonitorUpdate) ClearSnapshots() *RelayMonitorUpdate {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to RelayRateSnapshot entities by IDs.
func (_u *RelayMonitorUpdate) RemoveSnapshotIDs(ids ...int64) *RelayMonitorUpdate {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to RelayRateSnapshot entities.
func (_u *RelayMonitorUpdate) RemoveSnapshots(v ...*RelayRateSnapshot) *RelayMonitorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearChanges clears all "changes" edges to the RelayRateChange entity.
func (_u *RelayMonitorUpdate) ClearChanges() *RelayMonitorUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// RemoveChangeIDs removes the "changes" edge to RelayRateChange entities by IDs.
func (_u *RelayMonitorUpdate) RemoveChangeIDs(ids ...int64) *RelayMonitorUpdate {
	_u.mutation.RemoveChangeIDs(ids...)
	return _u
}

// RemoveChanges removes "changes" edges to RelayRateChange entities.
func (_u *RelayMonitorUpdate) RemoveChanges(v ...*RelayRateChange) *RelayMonitorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelayMonitorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayMonitorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelayMonitorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayMonitorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayMonitorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relaymonitor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayMonitorUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := relaymonitor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.System(); ok {
		if err := relaymonitor.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.system": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := relaymonitor.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := relaymonitor.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalSeconds(); ok {
		if err := relaymonitor.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := relaymonitor.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.last_error": %w`, err)}
		}
	}
	return nil
}

func (_u *RelayMonitorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaymonitor.Table, relaymonitor.Columns, sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaymonitor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaymonitor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(relaymonitor.FieldSystem, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(relaymonitor.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(relaymonitor.FieldVendor, field.TypeString, value)
	}
	if _u.mutation.VendorCleared() {
		_spec.ClearField(relaymonitor.FieldVendor, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialEncrypted(); ok {
		_spec.SetField(relaymonitor.FieldCredentialEncrypted, field.TypeString, value)
	}
	if _u.mutation.CredentialEncryptedCleared() {
		_spec.ClearField(relaymonitor.FieldCredentialEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.WatchedGroups(); ok {
		_spec.SetField(relaymonitor.FieldWatchedGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWatchedGroups(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, relaymonitor.FieldWatchedGroups, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(relaymonitor.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(relaymonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(relaymonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(relaymonitor.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(relaymonitor.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(relaymonitor.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(relaymonitor.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(relaymonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(relaymonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.SnapshotsTable,
			Columns: []string{relaymonitor.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.SnapshotsTable,
			Columns: []string{relaymonitor.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.SnapshotsTable,
			Columns: []string{relaymonitor.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.ChangesTable,
			Columns: []string{relaymonitor.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangesIDs(); len(nodes) > 0 && !_u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.ChangesTable,
			Columns: []string{relaymonitor.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.ChangesTable,
			Columns: []string{relaymonitor.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaymonitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelayMonitorUpdateOne is the builder for updating a single RelayMonitor entity.
type RelayMonitorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelayMonitorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelayMonitorUpdateOne) SetUpdatedAt(v time.Time) *RelayMonitorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RelayMonitorUpdateOne) SetName(v string) *RelayMonitorUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableName(v *string) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSystem sets the "system" field.
func (_u *RelayMonitorUpdateOne) SetSystem(v relaymonitor.System) *RelayMonitorUpdateOne {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableSystem(v *relaymonitor.System) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *RelayMonitorUpdateOne) SetBaseURL(v string) *RelayMonitorUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableBaseURL(v *string) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *RelayMonitorUpdateOne) SetVendor(v string) *RelayMonitorUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableVendor(v *string) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// ClearVendor clears the value of the "vendor" field.
func (_u *RelayMonitorUpdateOne) ClearVendor() *RelayMonitorUpdateOne {
	_u.mutation.ClearVendor()
	return _u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_u *RelayMonitorUpdateOne) SetCredentialEncrypted(v string) *RelayMonitorUpdateOne {
	_u.mutation.SetCredentialEncrypted(v)
	return _u
}

// SetNillableCredentialEncrypted sets the "credential_encrypted" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableCredentialEncrypted(v *string) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetCredentialEncrypted(*v)
	}
	return _u
}

// ClearCredentialEncrypted clears the value of the "credential_encrypted" field.
func (_u *RelayMonitorUpdateOne) ClearCredentialEncrypted() *RelayMonitorUpdateOne {
	_u.mutation.ClearCredentialEncrypted()
	return _u
}

// SetWatchedGroups sets the "watched_groups" field.
func (_u *RelayMonitorUpdateOne) SetWatchedGroups(v []string) *RelayMonitorUpdateOne {
	_u.mutation.SetWatchedGroups(v)
	return _u
}

// AppendWatchedGroups appends value to the "watched_groups" field.
func (_u *RelayMonitorUpdateOne) AppendWatchedGroups(v []string) *RelayMonitorUpdateOne {
	_u.mutation.AppendWatchedGroups(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RelayMonitorUpdateOne) SetEnabled(v bool) *RelayMonitorUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableEnabled(v *bool) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *RelayMonitorUpdateOne) SetIntervalSeconds(v int) *RelayMonitorUpdateOne {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableIntervalSeconds(v *int) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *RelayMonitorUpdateOne) AddIntervalSeconds(v int) *RelayMonitorUpdateOne {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *RelayMonitorUpdateOne) SetLastCheckedAt(v time.Time) *RelayMonitorUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableLastCheckedAt(v *time.Time) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *RelayMonitorUpdateOne) ClearLastCheckedAt() *RelayMonitorUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *RelayMonitorUpdateOne) SetLastError(v string) *RelayMonitorUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableLastError(v *string) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *RelayMonitorUpdateOne) ClearLastError() *RelayMonitorUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RelayMonitorUpdateOne) SetCreatedBy(v int64) *RelayMonitorUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RelayMonitorUpdateOne) SetNillableCreatedBy(v *int64) *RelayMonitorUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RelayMonitorUpdateOne) AddCreatedBy(v int64) *RelayMonitorUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddSnapshotIDs adds the "snapshots" edge to the RelayRateSnapshot entity by IDs.
func (_u *RelayMonitorUpdateOne) AddSnapshotIDs(ids ...int64) *RelayMonitorUpdateOne {
	_u.mutation.AddSnapshotIDs(ids...)
	return _u
}

// AddSnapshots adds the "snapshots" edges to the RelayRateSnapshot entity.
func (_u *RelayMonitorUpdateOne) AddSnapshots(v ...*RelayRateSnapshot) *RelayMonitorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSnapshotIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the RelayRateChange entity by IDs.
func (_u *RelayMonitorUpdateOne) AddChangeIDs(ids ...int64) *RelayMonitorUpdateOne {
	_u.mutation.AddChangeIDs(ids...)
	return _u
}

// AddChanges adds the "changes" edges to the RelayRateChange entity.
func (_u *RelayMonitorUpdateOne) AddChanges(v ...*RelayRateChange) *RelayMonitorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeIDs(ids...)
}

// Mutation returns the RelayMonitorMutation object of the builder.
func (_u *RelayMonitorUpdateOne) Mutation() *RelayMonitorMutation {
	return _u.mutation
}

// ClearSnapshots clears all "snapshots" edges to the RelayRateSnapshot entity.
func (_u *RelayMonitorUpdateOne) ClearSnapshots() *RelayMonitorUpdateOne {
	_u.mutation.ClearSnapshots()
	return _u
}

// RemoveSnapshotIDs removes the "snapshots" edge to RelayRateSnapshot entities by IDs.
func (_u *RelayMonitorUpdateOne) RemoveSnapshotIDs(ids ...int64) *RelayMonitorUpdateOne {
	_u.mutation.RemoveSnapshotIDs(ids...)
	return _u
}

// RemoveSnapshots removes "snapshots" edges to RelayRateSnapshot entities.
func (_u *RelayMonitorUpdateOne) RemoveSnapshots(v ...*RelayRateSnapshot) *RelayMonitorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSnapshotIDs(ids...)
}

// ClearChanges clears all "changes" edges to the RelayRateChange entity.
func (_u *RelayMonitorUpdateOne) ClearChanges() *RelayMonitorUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// RemoveChangeIDs removes the "changes" edge to RelayRateChange entities by IDs.
func (_u *RelayMonitorUpdateOne) RemoveChangeIDs(ids ...int64) *RelayMonitorUpdateOne {
	_u.mutation.RemoveChangeIDs(ids...)
	return _u
}

// RemoveChanges removes "changes" edges to RelayRateChange entities.
func (_u *RelayMonitorUpdateOne) RemoveChanges(v ...*RelayRateChange) *RelayMonitorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeIDs(ids...)
}

// Where appends a list predicates to the RelayMonitorUpdate builder.
func (_u *RelayMonitorUpdateOne) Where(ps ...predicate.RelayMonitor) *RelayMonitorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelayMonitorUpdateOne) Select(field string, fields ...string) *RelayMonitorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelayMonitor entity.
func (_u *RelayMonitorUpdateOne) Save(ctx context.Context) (*RelayMonitor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayMonitorUpdateOne) SaveX(ctx context.Context) *RelayMonitor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelayMonitorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayMonitorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelayMonitorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relaymonitor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayMonitorUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := relaymonitor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.System(); ok {
		if err := relaymonitor.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.system": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := relaymonitor.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := relaymonitor.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalSeconds(); ok {
		if err := relaymonitor.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.interval_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := relaymonitor.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "RelayMonitor.last_error": %w`, err)}
		}
	}
	return nil
}

func (_u *RelayMonitorUpdateOne) sqlSave(ctx context.Context) (_node *RelayMonitor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relaymonitor.Table, relaymonitor.Columns, sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelayMonitor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relaymonitor.FieldID)
		for _, f := range fields {
			if !relaymonitor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relaymonitor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relaymonitor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(relaymonitor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(relaymonitor.FieldSystem, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(relaymonitor.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(relaymonitor.FieldVendor, field.TypeString, value)
	}
	if _u.mutation.VendorCleared() {
		_spec.ClearField(relaymonitor.FieldVendor, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialEncrypted(); ok {
		_spec.SetField(relaymonitor.FieldCredentialEncrypted, field.TypeString, value)
	}
	if _u.mutation.CredentialEncryptedCleared() {
		_spec.ClearField(relaymonitor.FieldCredentialEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.WatchedGroups(); ok {
		_spec.SetField(relaymonitor.FieldWatchedGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWatchedGroups(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, relaymonitor.FieldWatchedGroups, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(relaymonitor.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(relaymonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(relaymonitor.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(relaymonitor.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(relaymonitor.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(relaymonitor.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(relaymonitor.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(relaymonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(relaymonitor.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.SnapshotsTable,
			Columns: []string{relaymonitor.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSnapshotsIDs(); len(nodes) > 0 && !_u.mutation.SnapshotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.SnapshotsTable,
			Columns: []string{relaymonitor.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.SnapshotsTable,
			Columns: []string{relaymonitor.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.ChangesTable,
			Columns: []string{relaymonitor.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangesIDs(); len(nodes) > 0 && !_u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.ChangesTable,
			Columns: []string{relaymonitor.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relaymonitor.ChangesTable,
			Columns: []string{relaymonitor.ChangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RelayMonitor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relaymonitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
