// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratechange"
)

// RelayRateChangeUpdate is the builder for updating RelayRateChange entities.
type RelayRateChangeUpdate struct {
	config
	hooks    []Hook
	mutation *RelayRateChangeMutation
}

// Where appends a list predicates to the RelayRateChangeUpdate builder.
func (_u *RelayRateChangeUpdate) Where(ps ...predicate.RelayRateChange) *RelayRateChangeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMonitorID sets the "monitor_id" field.
func (_u *RelayRateChangeUpdate) SetMonitorID(v int64) *RelayRateChangeUpdate {
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableMonitorID(v *int64) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// SetSite sets the "site" field.
func (_u *RelayRateChangeUpdate) SetSite(v string) *RelayRateChangeUpdate {
	_u.mutation.SetSite(v)
	return _u
}

// SetNillableSite sets the "site" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableSite(v *string) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetSite(*v)
	}
	return _u
}

// SetSystem sets the "system" field.
func (_u *RelayRateChangeUpdate) SetSystem(v string) *RelayRateChangeUpdate {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableSystem(v *string) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *RelayRateChangeUpdate) SetVendor(v string) *RelayRateChangeUpdate {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableVendor(v *string) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// ClearVendor clears the value of the "vendor" field.
func (_u *RelayRateChangeUpdate) ClearVendor() *RelayRateChangeUpdate {
	_u.mutation.ClearVendor()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *RelayRateChangeUpdate) SetGroupName(v string) *RelayRateChangeUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableGroupName(v *string) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetOldRate sets the "old_rate" field.
func (_u *RelayRateChangeUpdate) SetOldRate(v float64) *RelayRateChangeUpdate {
	_u.mutation.ResetOldRate()
	_u.mutation.SetOldRate(v)
	return _u
}

// SetNillableOldRate sets the "old_rate" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableOldRate(v *float64) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetOldRate(*v)
	}
	return _u
}

// AddOldRate adds value to the "old_rate" field.
func (_u *RelayRateChangeUpdate) AddOldRate(v float64) *RelayRateChangeUpdate {
	_u.mutation.AddOldRate(v)
	return _u
}

// SetNewRate sets the "new_rate" field.
func (_u *RelayRateChangeUpdate) SetNewRate(v float64) *RelayRateChangeUpdate {
	_u.mutation.ResetNewRate()
	_u.mutation.SetNewRate(v)
	return _u
}

// SetNillableNewRate sets the "new_rate" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableNewRate(v *float64) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetNewRate(*v)
	}
	return _u
}

// AddNewRate adds value to the "new_rate" field.
func (_u *RelayRateChangeUpdate) AddNewRate(v float64) *RelayRateChangeUpdate {
	_u.mutation.AddNewRate(v)
	return _u
}

// SetDirection sets the "direction" field.
func (_u *RelayRateChangeUpdate) SetDirection(v relayratechange.Direction) *RelayRateChangeUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableDirection(v *relayratechange.Direction) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *RelayRateChangeUpdate) SetContent(v string) *RelayRateChangeUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableContent(v *string) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *RelayRateChangeUpdate) ClearContent() *RelayRateChangeUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetDetectedAt sets the "detected_at" field.
func (_u *RelayRateChangeUpdate) SetDetectedAt(v time.Time) *RelayRateChangeUpdate {
	_u.mutation.SetDetectedAt(v)
	return _u
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_u *RelayRateChangeUpdate) SetNillableDetectedAt(v *time.Time) *RelayRateChangeUpdate {
	if v != nil {
		_u.SetDetectedAt(*v)
	}
	return _u
}

// SetMonitor sets the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateChangeUpdate) SetMonitor(v *RelayMonitor) *RelayRateChangeUpdate {
	return _u.SetMonitorID(v.ID)
}

// Mutation returns the RelayRateChangeMutation object of the builder.
func (_u *RelayRateChangeUpdate) Mutation() *RelayRateChangeMutation {
	return _u.mutation
}

// ClearMonitor clears the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateChangeUpdate) ClearMonitor() *RelayRateChangeUpdate {
	_u.mutation.ClearMonitor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelayRateChangeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayRateChangeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelayRateChangeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayRateChangeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayRateChangeUpdate) check() error {
	if v, ok := _u.mutation.Site(); ok {
		if err := relayratechange.SiteValidator(v); err != nil {
			return &ValidationError{Name: "site", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.site": %w`, err)}
		}
	}
	if v, ok := _u.mutation.System(); ok {
		if err := relayratechange.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.system": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := relayratechange.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := relayratechange.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := relayratechange.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := relayratechange.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.content": %w`, err)}
		}
	}
	if _u.mutation.MonitorCleared() && len(_u.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayRateChange.monitor"`)
	}
	return nil
}

func (_u *RelayRateChangeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relayratechange.Table, relayratechange.Columns, sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Site(); ok {
		_spec.SetField(relayratechange.FieldSite, field.TypeString, value)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(relayratechange.FieldSystem, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(relayratechange.FieldVendor, field.TypeString, value)
	}
	if _u.mutation.VendorCleared() {
		_spec.ClearField(relayratechange.FieldVendor, field.TypeString)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(relayratechange.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldRate(); ok {
		_spec.SetField(relayratechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOldRate(); ok {
		_spec.AddField(relayratechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NewRate(); ok {
		_spec.SetField(relayratechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNewRate(); ok {
		_spec.AddField(relayratechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(relayratechange.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(relayratechange.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(relayratechange.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.DetectedAt(); ok {
		_spec.SetField(relayratechange.FieldDetectedAt, field.TypeTime, value)
	}
	if _u.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratechange.MonitorTable,
			Columns: []string{relayratechange.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratechange.MonitorTable,
			Columns: []string{relayratechange.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relayratechange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelayRateChangeUpdateOne is the builder for updating a single RelayRateChange entity.
type RelayRateChangeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelayRateChangeMutation
}

// SetMonitorID sets the "monitor_id" field.
func (_u *RelayRateChangeUpdateOne) SetMonitorID(v int64) *RelayRateChangeUpdateOne {
	_u.mutation.SetMonitorID(v)
	return _u
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableMonitorID(v *int64) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetMonitorID(*v)
	}
	return _u
}

// SetSite sets the "site" field.
func (_u *RelayRateChangeUpdateOne) SetSite(v string) *RelayRateChangeUpdateOne {
	_u.mutation.SetSite(v)
	return _u
}

// SetNillableSite sets the "site" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableSite(v *string) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetSite(*v)
	}
	return _u
}

// SetSystem sets the "system" field.
func (_u *RelayRateChangeUpdateOne) SetSystem(v string) *RelayRateChangeUpdateOne {
	_u.mutation.SetSystem(v)
	return _u
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableSystem(v *string) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetSystem(*v)
	}
	return _u
}

// SetVendor sets the "vendor" field.
func (_u *RelayRateChangeUpdateOne) SetVendor(v string) *RelayRateChangeUpdateOne {
	_u.mutation.SetVendor(v)
	return _u
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableVendor(v *string) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetVendor(*v)
	}
	return _u
}

// ClearVendor clears the value of the "vendor" field.
func (_u *RelayRateChangeUpdateOne) ClearVendor() *RelayRateChangeUpdateOne {
	_u.mutation.ClearVendor()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *RelayRateChangeUpdateOne) SetGroupName(v string) *RelayRateChangeUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableGroupName(v *string) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// SetOldRate sets the "old_rate" field.
func (_u *RelayRateChangeUpdateOne) SetOldRate(v float64) *RelayRateChangeUpdateOne {
	_u.mutation.ResetOldRate()
	_u.mutation.SetOldRate(v)
	return _u
}

// SetNillableOldRate sets the "old_rate" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableOldRate(v *float64) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetOldRate(*v)
	}
	return _u
}

// AddOldRate adds value to the "old_rate" field.
func (_u *RelayRateChangeUpdateOne) AddOldRate(v float64) *RelayRateChangeUpdateOne {
	_u.mutation.AddOldRate(v)
	return _u
}

// SetNewRate sets the "new_rate" field.
func (_u *RelayRateChangeUpdateOne) SetNewRate(v float64) *RelayRateChangeUpdateOne {
	_u.mutation.ResetNewRate()
	_u.mutation.SetNewRate(v)
	return _u
}

// SetNillableNewRate sets the "new_rate" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableNewRate(v *float64) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetNewRate(*v)
	}
	return _u
}

// AddNewRate adds value to the "new_rate" field.
func (_u *RelayRateChangeUpdateOne) AddNewRate(v float64) *RelayRateChangeUpdateOne {
	_u.mutation.AddNewRate(v)
	return _u
}

// SetDirection sets the "direction" field.
func (_u *RelayRateChangeUpdateOne) SetDirection(v relayratechange.Direction) *RelayRateChangeUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableDirection(v *relayratechange.Direction) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *RelayRateChangeUpdateOne) SetContent(v string) *RelayRateChangeUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableContent(v *string) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *RelayRateChangeUpdateOne) ClearContent() *RelayRateChangeUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetDetectedAt sets the "detected_at" field.
func (_u *RelayRateChangeUpdateOne) SetDetectedAt(v time.Time) *RelayRateChangeUpdateOne {
	_u.mutation.SetDetectedAt(v)
	return _u
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_u *RelayRateChangeUpdateOne) SetNillableDetectedAt(v *time.Time) *RelayRateChangeUpdateOne {
	if v != nil {
		_u.SetDetectedAt(*v)
	}
	return _u
}

// SetMonitor sets the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateChangeUpdateOne) SetMonitor(v *RelayMonitor) *RelayRateChangeUpdateOne {
	return _u.SetMonitorID(v.ID)
}

// Mutation returns the RelayRateChangeMutation object of the builder.
func (_u *RelayRateChangeUpdateOne) Mutation() *RelayRateChangeMutation {
	return _u.mutation
}

// ClearMonitor clears the "monitor" edge to the RelayMonitor entity.
func (_u *RelayRateChangeUpdateOne) ClearMonitor() *RelayRateChangeUpdateOne {
	_u.mutation.ClearMonitor()
	return _u
}

// Where appends a list predicates to the RelayRateChangeUpdate builder.
func (_u *RelayRateChangeUpdateOne) Where(ps ...predicate.RelayRateChange) *RelayRateChangeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelayRateChangeUpdateOne) Select(field string, fields ...string) *RelayRateChangeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelayRateChange entity.
func (_u *RelayRateChangeUpdateOne) Save(ctx context.Context) (*RelayRateChange, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelayRateChangeUpdateOne) SaveX(ctx context.Context) *RelayRateChange {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelayRateChangeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelayRateChangeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelayRateChangeUpdateOne) check() error {
	if v, ok := _u.mutation.Site(); ok {
		if err := relayratechange.SiteValidator(v); err != nil {
			return &ValidationError{Name: "site", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.site": %w`, err)}
		}
	}
	if v, ok := _u.mutation.System(); ok {
		if err := relayratechange.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.system": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Vendor(); ok {
		if err := relayratechange.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.vendor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := relayratechange.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := relayratechange.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := relayratechange.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.content": %w`, err)}
		}
	}
	if _u.mutation.MonitorCleared() && len(_u.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RelayRateChange.monitor"`)
	}
	return nil
}

func (_u *RelayRateChangeUpdateOne) sqlSave(ctx context.Context) (_node *RelayRateChange, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relayratechange.Table, relayratechange.Columns, sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelayRateChange.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relayratechange.FieldID)
		for _, f := range fields {
			if !relayratechange.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relayratechange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Site(); ok {
		_spec.SetField(relayratechange.FieldSite, field.TypeString, value)
	}
	if value, ok := _u.mutation.System(); ok {
		_spec.SetField(relayratechange.FieldSystem, field.TypeString, value)
	}
	if value, ok := _u.mutation.Vendor(); ok {
		_spec.SetField(relayratechange.FieldVendor, field.TypeString, value)
	}
	if _u.mutation.VendorCleared() {
		_spec.ClearField(relayratechange.FieldVendor, field.TypeString)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(relayratechange.FieldGroupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldRate(); ok {
		_spec.SetField(relayratechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOldRate(); ok {
		_spec.AddField(relayratechange.FieldOldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NewRate(); ok {
		_spec.SetField(relayratechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNewRate(); ok {
		_spec.AddField(relayratechange.FieldNewRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(relayratechange.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(relayratechange.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(relayratechange.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.DetectedAt(); ok {
		_spec.SetField(relayratechange.FieldDetectedAt, field.TypeTime, value)
	}
	if _u.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratechange.MonitorTable,
			Columns: []string{relayratechange.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratechange.MonitorTable,
			Columns: []string{relayratechange.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RelayRateChange{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relayratechange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
