// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/relaymonitor"
	"github.com/Wei-Shaw/sub2api/ent/relayratechange"
)

// RelayRateChangeCreate is the builder for creating a RelayRateChange entity.
type RelayRateChangeCreate struct {
	config
	mutation *RelayRateChangeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMonitorID sets the "monitor_id" field.
func (_c *RelayRateChangeCreate) SetMonitorID(v int64) *RelayRateChangeCreate {
	_c.mutation.SetMonitorID(v)
	return _c
}

// SetSite sets the "site" field.
func (_c *RelayRateChangeCreate) SetSite(v string) *RelayRateChangeCreate {
	_c.mutation.SetSite(v)
	return _c
}

// SetSystem sets the "system" field.
func (_c *RelayRateChangeCreate) SetSystem(v string) *RelayRateChangeCreate {
	_c.mutation.SetSystem(v)
	return _c
}

// SetVendor sets the "vendor" field.
func (_c *RelayRateChangeCreate) SetVendor(v string) *RelayRateChangeCreate {
	_c.mutation.SetVendor(v)
	return _c
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_c *RelayRateChangeCreate) SetNillableVendor(v *string) *RelayRateChangeCreate {
	if v != nil {
		_c.SetVendor(*v)
	}
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *RelayRateChangeCreate) SetGroupName(v string) *RelayRateChangeCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetOldRate sets the "old_rate" field.
func (_c *RelayRateChangeCreate) SetOldRate(v float64) *RelayRateChangeCreate {
	_c.mutation.SetOldRate(v)
	return _c
}

// SetNewRate sets the "new_rate" field.
func (_c *RelayRateChangeCreate) SetNewRate(v float64) *RelayRateChangeCreate {
	_c.mutation.SetNewRate(v)
	return _c
}

// SetDirection sets the "direction" field.
func (_c *RelayRateChangeCreate) SetDirection(v relayratechange.Direction) *RelayRateChangeCreate {
	_c.mutation.SetDirection(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *RelayRateChangeCreate) SetContent(v string) *RelayRateChangeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *RelayRateChangeCreate) SetNillableContent(v *string) *RelayRateChangeCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetDetectedAt sets the "detected_at" field.
func (_c *RelayRateChangeCreate) SetDetectedAt(v time.Time) *RelayRateChangeCreate {
	_c.mutation.SetDetectedAt(v)
	return _c
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_c *RelayRateChangeCreate) SetNillableDetectedAt(v *time.Time) *RelayRateChangeCreate {
	if v != nil {
		_c.SetDetectedAt(*v)
	}
	return _c
}

// SetMonitor sets the "monitor" edge to the RelayMonitor entity.
func (_c *RelayRateChangeCreate) SetMonitor(v *RelayMonitor) *RelayRateChangeCreate {
	return _c.SetMonitorID(v.ID)
}

// Mutation returns the RelayRateChangeMutation object of the builder.
func (_c *RelayRateChangeCreate) Mutation() *RelayRateChangeMutation {
	return _c.mutation
}

// Save creates the RelayRateChange in the database.
func (_c *RelayRateChangeCreate) Save(ctx context.Context) (*RelayRateChange, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelayRateChangeCreate) SaveX(ctx context.Context) *RelayRateChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayRateChangeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayRateChangeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelayRateChangeCreate) defaults() {
	if _, ok := _c.mutation.Vendor(); !ok {
		v := relayratechange.DefaultVendor
		_c.mutation.SetVendor(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := relayratechange.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.DetectedAt(); !ok {
		v := relayratechange.DefaultDetectedAt()
		_c.mutation.SetDetectedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelayRateChangeCreate) check() error {
	if _, ok := _c.mutation.MonitorID(); !ok {
		return &ValidationError{Name: "monitor_id", err: errors.New(`ent: missing required field "RelayRateChange.monitor_id"`)}
	}
	if _, ok := _c.mutation.Site(); !ok {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required field "RelayRateChange.site"`)}
	}
	if v, ok := _c.mutation.Site(); ok {
		if err := relayratechange.SiteValidator(v); err != nil {
			return &ValidationError{Name: "site", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.site": %w`, err)}
		}
	}
	if _, ok := _c.mutation.System(); !ok {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required field "RelayRateChange.system"`)}
	}
	if v, ok := _c.mutation.System(); ok {
		if err := relayratechange.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.system": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Vendor(); ok {
		if err := relayratechange.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.vendor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "RelayRateChange.group_name"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := relayratechange.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OldRate(); !ok {
		return &ValidationError{Name: "old_rate", err: errors.New(`ent: missing required field "RelayRateChange.old_rate"`)}
	}
	if _, ok := _c.mutation.NewRate(); !ok {
		return &ValidationError{Name: "new_rate", err: errors.New(`ent: missing required field "RelayRateChange.new_rate"`)}
	}
	if _, ok := _c.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "RelayRateChange.direction"`)}
	}
	if v, ok := _c.mutation.Direction(); ok {
		if err := relayratechange.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.direction": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := relayratechange.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "RelayRateChange.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DetectedAt(); !ok {
		return &ValidationError{Name: "detected_at", err: errors.New(`ent: missing required field "RelayRateChange.detected_at"`)}
	}
	if len(_c.mutation.MonitorIDs()) == 0 {
		return &ValidationError{Name: "monitor", err: errors.New(`ent: missing required edge "RelayRateChange.monitor"`)}
	}
	return nil
}

func (_c *RelayRateChangeCreate) sqlSave(ctx context.Context) (*RelayRateChange, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelayRateChangeCreate) createSpec() (*RelayRateChange, *sqlgraph.CreateSpec) {
	var (
		_node = &RelayRateChange{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relayratechange.Table, sqlgraph.NewFieldSpec(relayratechange.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Site(); ok {
		_spec.SetField(relayratechange.FieldSite, field.TypeString, value)
		_node.Site = value
	}
	if value, ok := _c.mutation.System(); ok {
		_spec.SetField(relayratechange.FieldSystem, field.TypeString, value)
		_node.System = value
	}
	if value, ok := _c.mutation.Vendor(); ok {
		_spec.SetField(relayratechange.FieldVendor, field.TypeString, value)
		_node.Vendor = value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(relayratechange.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := _c.mutation.OldRate(); ok {
		_spec.SetField(relayratechange.FieldOldRate, field.TypeFloat64, value)
		_node.OldRate = value
	}
	if value, ok := _c.mutation.NewRate(); ok {
		_spec.SetField(relayratechange.FieldNewRate, field.TypeFloat64, value)
		_node.NewRate = value
	}
	if value, ok := _c.mutation.Direction(); ok {
		_spec.SetField(relayratechange.FieldDirection, field.TypeEnum, value)
		_node.Direction = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(relayratechange.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.DetectedAt(); ok {
		_spec.SetField(relayratechange.FieldDetectedAt, field.TypeTime, value)
		_node.DetectedAt = value
	}
	if nodes := _c.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relayratechange.MonitorTable,
			Columns: []string{relayratechange.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relaymonitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MonitorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayRateChange.Create().
//		SetMonitorID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayRateChangeUpsert) {
//			SetMonitorID(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayRateChangeCreate) OnConflict(opts ...sql.ConflictOption) *RelayRateChangeUpsertOne {
	_c.conflict = opts
	return &RelayRateChangeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayRateChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayRateChangeCreate) OnConflictColumns(columns ...string) *RelayRateChangeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayRateChangeUpsertOne{
		create: _c,
	}
}

type (
	// RelayRateChangeUpsertOne is the builder for "upsert"-ing
	//  one RelayRateChange node.
	RelayRateChangeUpsertOne struct {
		create *RelayRateChangeCreate
	}

	// RelayRateChangeUpsert is the "OnConflict" setter.
	RelayRateChangeUpsert struct {
		*sql.UpdateSet
	}
)

// SetMonitorID sets the "monitor_id" field.
func (u *RelayRateChangeUpsert) SetMonitorID(v int64) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldMonitorID, v)
	return u
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateMonitorID() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldMonitorID)
	return u
}

// SetSite sets the "site" field.
func (u *RelayRateChangeUpsert) SetSite(v string) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldSite, v)
	return u
}

// UpdateSite sets the "site" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateSite() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldSite)
	return u
}

// SetSystem sets the "system" field.
func (u *RelayRateChangeUpsert) SetSystem(v string) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldSystem, v)
	return u
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateSystem() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldSystem)
	return u
}

// SetVendor sets the "vendor" field.
func (u *RelayRateChangeUpsert) SetVendor(v string) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldVendor, v)
	return u
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateVendor() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldVendor)
	return u
}

// ClearVendor clears the value of the "vendor" field.
func (u *RelayRateChangeUpsert) ClearVendor() *RelayRateChangeUpsert {
	u.SetNull(relayratechange.FieldVendor)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *RelayRateChangeUpsert) SetGroupName(v string) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateGroupName() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldGroupName)
	return u
}

// SetOldRate sets the "old_rate" field.
func (u *RelayRateChangeUpsert) SetOldRate(v float64) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldOldRate, v)
	return u
}

// UpdateOldRate sets the "old_rate" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateOldRate() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldOldRate)
	return u
}

// AddOldRate adds v to the "old_rate" field.
func (u *RelayRateChangeUpsert) AddOldRate(v float64) *RelayRateChangeUpsert {
	u.Add(relayratechange.FieldOldRate, v)
	return u
}

// SetNewRate sets the "new_rate" field.
func (u *RelayRateChangeUpsert) SetNewRate(v float64) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldNewRate, v)
	return u
}

// UpdateNewRate sets the "new_rate" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateNewRate() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldNewRate)
	return u
}

// AddNewRate adds v to the "new_rate" field.
func (u *RelayRateChangeUpsert) AddNewRate(v float64) *RelayRateChangeUpsert {
	u.Add(relayratechange.FieldNewRate, v)
	return u
}

// SetDirection sets the "direction" field.
func (u *RelayRateChangeUpsert) SetDirection(v relayratechange.Direction) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldDirection, v)
	return u
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateDirection() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldDirection)
	return u
}

// SetContent sets the "content" field.
func (u *RelayRateChangeUpsert) SetContent(v string) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateContent() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *RelayRateChangeUpsert) ClearContent() *RelayRateChangeUpsert {
	u.SetNull(relayratechange.FieldContent)
	return u
}

// SetDetectedAt sets the "detected_at" field.
func (u *RelayRateChangeUpsert) SetDetectedAt(v time.Time) *RelayRateChangeUpsert {
	u.Set(relayratechange.FieldDetectedAt, v)
	return u
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *RelayRateChangeUpsert) UpdateDetectedAt() *RelayRateChangeUpsert {
	u.SetExcluded(relayratechange.FieldDetectedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RelayRateChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayRateChangeUpsertOne) UpdateNewValues() *RelayRateChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayRateChange.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RelayRateChangeUpsertOne) Ignore() *RelayRateChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayRateChangeUpsertOne) DoNothing() *RelayRateChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayRateChangeCreate.OnConflict
// documentation for more info.
func (u *RelayRateChangeUpsertOne) Update(set func(*RelayRateChangeUpsert)) *RelayRateChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayRateChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetMonitorID sets the "monitor_id" field.
func (u *RelayRateChangeUpsertOne) SetMonitorID(v int64) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateMonitorID() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateMonitorID()
	})
}

// SetSite sets the "site" field.
func (u *RelayRateChangeUpsertOne) SetSite(v string) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetSite(v)
	})
}

// UpdateSite sets the "site" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateSite() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateSite()
	})
}

// SetSystem sets the "system" field.
func (u *RelayRateChangeUpsertOne) SetSystem(v string) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateSystem() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateSystem()
	})
}

// SetVendor sets the "vendor" field.
func (u *RelayRateChangeUpsertOne) SetVendor(v string) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateVendor() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateVendor()
	})
}

// ClearVendor clears the value of the "vendor" field.
func (u *RelayRateChangeUpsertOne) ClearVendor() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.ClearVendor()
	})
}

// SetGroupName sets the "group_name" field.
func (u *RelayRateChangeUpsertOne) SetGroupName(v string) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateGroupName() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateGroupName()
	})
}

// SetOldRate sets the "old_rate" field.
func (u *RelayRateChangeUpsertOne) SetOldRate(v float64) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetOldRate(v)
	})
}

// AddOldRate adds v to the "old_rate" field.
func (u *RelayRateChangeUpsertOne) AddOldRate(v float64) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.AddOldRate(v)
	})
}

// UpdateOldRate sets the "old_rate" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateOldRate() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateOldRate()
	})
}

// SetNewRate sets the "new_rate" field.
func (u *RelayRateChangeUpsertOne) SetNewRate(v float64) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetNewRate(v)
	})
}

// AddNewRate adds v to the "new_rate" field.
func (u *RelayRateChangeUpsertOne) AddNewRate(v float64) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.AddNewRate(v)
	})
}

// UpdateNewRate sets the "new_rate" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateNewRate() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateNewRate()
	})
}

// SetDirection sets the "direction" field.
func (u *RelayRateChangeUpsertOne) SetDirection(v relayratechange.Direction) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateDirection() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateDirection()
	})
}

// SetContent sets the "content" field.
func (u *RelayRateChangeUpsertOne) SetContent(v string) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateContent() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *RelayRateChangeUpsertOne) ClearContent() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.ClearContent()
	})
}

// SetDetectedAt sets the "detected_at" field.
func (u *RelayRateChangeUpsertOne) SetDetectedAt(v time.Time) *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetDetectedAt(v)
	})
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *RelayRateChangeUpsertOne) UpdateDetectedAt() *RelayRateChangeUpsertOne {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateDetectedAt()
	})
}

// Exec executes the query.
func (u *RelayRateChangeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayRateChangeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayRateChangeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RelayRateChangeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RelayRateChangeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RelayRateChangeCreateBulk is the builder for creating many RelayRateChange entities in bulk.
type RelayRateChangeCreateBulk struct {
	config
	err      error
	builders []*RelayRateChangeCreate
	conflict []sql.ConflictOption
}

// Save creates the RelayRateChange entities in the database.
func (_c *RelayRateChangeCreateBulk) Save(ctx context.Context) ([]*RelayRateChange, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelayRateChange, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelayRateChangeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelayRateChangeCreateBulk) SaveX(ctx context.Context) []*RelayRateChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelayRateChangeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelayRateChangeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RelayRateChange.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RelayRateChangeUpsert) {
//			SetMonitorID(v+v).
//		}).
//		Exec(ctx)
func (_c *RelayRateChangeCreateBulk) OnConflict(opts ...sql.ConflictOption) *RelayRateChangeUpsertBulk {
	_c.conflict = opts
	return &RelayRateChangeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RelayRateChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RelayRateChangeCreateBulk) OnConflictColumns(columns ...string) *RelayRateChangeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RelayRateChangeUpsertBulk{
		create: _c,
	}
}

// RelayRateChangeUpsertBulk is the builder for "upsert"-ing
// a bulk of RelayRateChange nodes.
type RelayRateChangeUpsertBulk struct {
	create *RelayRateChangeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RelayRateChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RelayRateChangeUpsertBulk) UpdateNewValues() *RelayRateChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RelayRateChange.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RelayRateChangeUpsertBulk) Ignore() *RelayRateChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RelayRateChangeUpsertBulk) DoNothing() *RelayRateChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RelayRateChangeCreateBulk.OnConflict
// documentation for more info.
func (u *RelayRateChangeUpsertBulk) Update(set func(*RelayRateChangeUpsert)) *RelayRateChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RelayRateChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetMonitorID sets the "monitor_id" field.
func (u *RelayRateChangeUpsertBulk) SetMonitorID(v int64) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateMonitorID() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateMonitorID()
	})
}

// SetSite sets the "site" field.
func (u *RelayRateChangeUpsertBulk) SetSite(v string) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetSite(v)
	})
}

// UpdateSite sets the "site" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateSite() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateSite()
	})
}

// SetSystem sets the "system" field.
func (u *RelayRateChangeUpsertBulk) SetSystem(v string) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateSystem() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateSystem()
	})
}

// SetVendor sets the "vendor" field.
func (u *RelayRateChangeUpsertBulk) SetVendor(v string) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateVendor() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateVendor()
	})
}

// ClearVendor clears the value of the "vendor" field.
func (u *RelayRateChangeUpsertBulk) ClearVendor() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.ClearVendor()
	})
}

// SetGroupName sets the "group_name" field.
func (u *RelayRateChangeUpsertBulk) SetGroupName(v string) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateGroupName() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateGroupName()
	})
}

// SetOldRate sets the "old_rate" field.
func (u *RelayRateChangeUpsertBulk) SetOldRate(v float64) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetOldRate(v)
	})
}

// AddOldRate adds v to the "old_rate" field.
func (u *RelayRateChangeUpsertBulk) AddOldRate(v float64) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.AddOldRate(v)
	})
}

// UpdateOldRate sets the "old_rate" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateOldRate() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateOldRate()
	})
}

// SetNewRate sets the "new_rate" field.
func (u *RelayRateChangeUpsertBulk) SetNewRate(v float64) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetNewRate(v)
	})
}

// AddNewRate adds v to the "new_rate" field.
func (u *RelayRateChangeUpsertBulk) AddNewRate(v float64) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.AddNewRate(v)
	})
}

// UpdateNewRate sets the "new_rate" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateNewRate() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateNewRate()
	})
}

// SetDirection sets the "direction" field.
func (u *RelayRateChangeUpsertBulk) SetDirection(v relayratechange.Direction) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateDirection() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateDirection()
	})
}

// SetContent sets the "content" field.
func (u *RelayRateChangeUpsertBulk) SetContent(v string) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateContent() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *RelayRateChangeUpsertBulk) ClearContent() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.ClearContent()
	})
}

// SetDetectedAt sets the "detected_at" field.
func (u *RelayRateChangeUpsertBulk) SetDetectedAt(v time.Time) *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.SetDetectedAt(v)
	})
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *RelayRateChangeUpsertBulk) UpdateDetectedAt() *RelayRateChangeUpsertBulk {
	return u.Update(func(s *RelayRateChangeUpsert) {
		s.UpdateDetectedAt()
	})
}

// Exec executes the query.
func (u *RelayRateChangeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RelayRateChangeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RelayRateChangeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RelayRateChangeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
